// -*- C++ -*-
#ifndef CMS5_H
#define CMS5_H
#include "Math/LorentzVector.h"
#include "Math/GenVector/PtEtaPhiM4D.h"
#include "Math/Point3D.h"
#include "TMath.h"
#include "TBranch.h"
#include "TTree.h"
#include "TH1F.h"
#include "TFile.h"
#include "TBits.h"
#include <vector>
#include <unistd.h>
typedef ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<float> > LorentzVector;

// Generated with file: /home/users/usarica/work/Width_AC_Run2/Samples/191212/VBF_HToZZTo2L2Nu_M900_13TeV_powheg2_JHUGenV7011_pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/allevents.root

using namespace std;
class CMS5 {
private:
protected:
  unsigned int index;
  float p_Gen_JJEW_SIG_ghza4_1_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghza4_1_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghza4_1_MCFM_isLoaded;
  vector<int> *ak8jets_partonFlavour_;
  TBranch *ak8jets_partonFlavour_branch;
  bool ak8jets_partonFlavour_isLoaded;
  float p_Gen_JJEW_BSI_ghv1_1_ghv2_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv1_1_ghv2_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv1_1_ghv2_1_MCFM_isLoaded;
  vector<float> *electrons_eta_;
  TBranch *electrons_eta_branch;
  bool electrons_eta_isLoaded;
  vector<float> *electrons_pfIso04_sum_charged_nofsr_;
  TBranch *electrons_pfIso04_sum_charged_nofsr_branch;
  bool electrons_pfIso04_sum_charged_nofsr_isLoaded;
  vector<float> *lheparticles_pz_;
  TBranch *lheparticles_pz_branch;
  bool lheparticles_pz_isLoaded;
  vector<bool> *ak4jets_pass_tightId_;
  TBranch *ak4jets_pass_tightId_branch;
  bool ak4jets_pass_tightId_isLoaded;
  vector<float> *lheparticles_py_;
  TBranch *lheparticles_py_branch;
  bool lheparticles_py_isLoaded;
  vector<unsigned int> *electrons_id_cutBased_Fall17V2_Veto_Bits_;
  TBranch *electrons_id_cutBased_Fall17V2_Veto_Bits_branch;
  bool electrons_id_cutBased_Fall17V2_Veto_Bits_isLoaded;
  float pfmet_metPhi_Nominal_;
  TBranch *pfmet_metPhi_Nominal_branch;
  bool pfmet_metPhi_Nominal_isLoaded;
  float xsec_;
  TBranch *xsec_branch;
  bool xsec_isLoaded;
  float p_Gen_GG_SIG_kappaTopBot_1_ghz1_1_MCFM_;
  TBranch *p_Gen_GG_SIG_kappaTopBot_1_ghz1_1_MCFM_branch;
  bool p_Gen_GG_SIG_kappaTopBot_1_ghz1_1_MCFM_isLoaded;
  float p_Gen_GG_BSI_kappaTopBot_1_ghz1_1_MCFM_;
  TBranch *p_Gen_GG_BSI_kappaTopBot_1_ghz1_1_MCFM_branch;
  bool p_Gen_GG_BSI_kappaTopBot_1_ghz1_1_MCFM_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_gha4_0p75_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_gha4_0p75_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_gha4_0p75_MCFM_isLoaded;
  vector<float> *electrons_miniIso_comb_nofsr_uncorrected_;
  TBranch *electrons_miniIso_comb_nofsr_uncorrected_branch;
  bool electrons_miniIso_comb_nofsr_uncorrected_isLoaded;
  vector<bool> *genparticles_isLastCopyBeforeFSR_;
  TBranch *genparticles_isLastCopyBeforeFSR_branch;
  bool genparticles_isLastCopyBeforeFSR_isLoaded;
  vector<float> *muons_pfIso04_comb_nofsr_;
  TBranch *muons_pfIso04_comb_nofsr_branch;
  bool muons_pfIso04_comb_nofsr_isLoaded;
  vector<bool> *isotracks_is_pfCand_;
  TBranch *isotracks_is_pfCand_branch;
  bool isotracks_is_pfCand_isLoaded;
  bool metfilter_CSCTightHaloFilter_;
  TBranch *metfilter_CSCTightHaloFilter_branch;
  bool metfilter_CSCTightHaloFilter_isLoaded;
  vector<float> *muons_time_rpc_IPInOut_;
  TBranch *muons_time_rpc_IPInOut_branch;
  bool muons_time_rpc_IPInOut_isLoaded;
  vector<float> *muons_pt_;
  TBranch *muons_pt_branch;
  bool muons_pt_isLoaded;
  float p_Gen_JJEW_SIG_gha4_1_MCFM_;
  TBranch *p_Gen_JJEW_SIG_gha4_1_MCFM_branch;
  bool p_Gen_JJEW_SIG_gha4_1_MCFM_isLoaded;
  vector<bool> *electrons_id_MVA_Fall17V2_NoIso_pass_wpLoose_;
  TBranch *electrons_id_MVA_Fall17V2_NoIso_pass_wpLoose_branch;
  bool electrons_id_MVA_Fall17V2_NoIso_pass_wpLoose_isLoaded;
  vector<float> *photons_scale_smear_corr_;
  TBranch *photons_scale_smear_corr_branch;
  bool photons_scale_smear_corr_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghv2_0p5_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghv2_0p5_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghv2_0p5_MCFM_isLoaded;
  vector<unsigned int> *electrons_fid_mask_;
  TBranch *electrons_fid_mask_branch;
  bool electrons_fid_mask_isLoaded;
  float LHEweight_AsMZ_Dn_default_;
  TBranch *LHEweight_AsMZ_Dn_default_branch;
  bool LHEweight_AsMZ_Dn_default_isLoaded;
  vector<float> *electrons_mass_;
  TBranch *electrons_mass_branch;
  bool electrons_mass_isLoaded;
  float pfmet_metPhi_JECDn_;
  TBranch *pfmet_metPhi_JECDn_branch;
  bool pfmet_metPhi_JECDn_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghv4_0p5_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghv4_0p5_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghv4_0p5_MCFM_isLoaded;
  vector<float> *ak4jets_JERDn_;
  TBranch *ak4jets_JERDn_branch;
  bool ak4jets_JERDn_isLoaded;
  float xsec_lhe_;
  TBranch *xsec_lhe_branch;
  bool xsec_lhe_isLoaded;
  vector<int> *ak4jets_partonFlavour_;
  TBranch *ak4jets_partonFlavour_branch;
  bool ak4jets_partonFlavour_isLoaded;
  vector<float> *ak4jets_eta_;
  TBranch *ak4jets_eta_branch;
  bool ak4jets_eta_isLoaded;
  vector<float> *ak4jets_totalMultiplicity_;
  TBranch *ak4jets_totalMultiplicity_branch;
  bool ak4jets_totalMultiplicity_isLoaded;
  float puppimet_metPhi_JECDn_;
  TBranch *puppimet_metPhi_JECDn_branch;
  bool puppimet_metPhi_JECDn_isLoaded;
  vector<float> *electrons_pt_;
  TBranch *electrons_pt_branch;
  bool electrons_pt_isLoaded;
  vector<float> *genparticles_pt_;
  TBranch *genparticles_pt_branch;
  bool genparticles_pt_isLoaded;
  float PythiaWeight_fsr_muR0p5_;
  TBranch *PythiaWeight_fsr_muR0p5_branch;
  bool PythiaWeight_fsr_muR0p5_isLoaded;
  vector<int> *genparticles_mom0_index_;
  TBranch *genparticles_mom0_index_branch;
  bool genparticles_mom0_index_isLoaded;
  float p_Gen_JJEW_SIG_ghv1prime2_1E4_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1prime2_1E4_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1prime2_1E4_MCFM_isLoaded;
  vector<float> *muons_pull_dxdz_noArb_DT_;
  TBranch *muons_pull_dxdz_noArb_DT_branch;
  bool muons_pull_dxdz_noArb_DT_isLoaded;
  vector<float> *ak8jets_totalMultiplicity_;
  TBranch *ak8jets_totalMultiplicity_branch;
  bool ak8jets_totalMultiplicity_isLoaded;
  float p_Gen_JJEW_BKG_MCFM_;
  TBranch *p_Gen_JJEW_BKG_MCFM_branch;
  bool p_Gen_JJEW_BKG_MCFM_isLoaded;
  float p_Gen_JJEW_BSI_gha2_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_gha2_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_gha2_1_MCFM_isLoaded;
  vector<bool> *isotracks_fromPV_;
  TBranch *isotracks_fromPV_branch;
  bool isotracks_fromPV_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_gha4_0p5_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_gha4_0p5_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_gha4_0p5_MCFM_isLoaded;
  float p_Gen_JJEW_BSI_ghv1_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv1_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv1_1_MCFM_isLoaded;
  vector<float> *muons_scale_smear_pt_corr_smear_totalUp_;
  TBranch *muons_scale_smear_pt_corr_smear_totalUp_branch;
  bool muons_scale_smear_pt_corr_smear_totalUp_isLoaded;
  vector<bool> *electrons_id_MVA_Fall17V2_NoIso_pass_wp80_;
  TBranch *electrons_id_MVA_Fall17V2_NoIso_pass_wp80_branch;
  bool electrons_id_MVA_Fall17V2_NoIso_pass_wp80_isLoaded;
  vector<float> *isotracks_pfIso03_comb_nofsr_;
  TBranch *isotracks_pfIso03_comb_nofsr_branch;
  bool isotracks_pfIso03_comb_nofsr_isLoaded;
  unsigned int LuminosityBlock_;
  TBranch *LuminosityBlock_branch;
  bool LuminosityBlock_isLoaded;
  unsigned int vtxs_nvtxs_;
  TBranch *vtxs_nvtxs_branch;
  bool vtxs_nvtxs_isLoaded;
  float qscale_;
  TBranch *qscale_branch;
  bool qscale_isLoaded;
  float p_Gen_JJEW_BSI_ghv1_1_ghza4_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv1_1_ghza4_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv1_1_ghza4_1_MCFM_isLoaded;
  vector<float> *muons_time_rpc_IPInOutError_;
  TBranch *muons_time_rpc_IPInOutError_branch;
  bool muons_time_rpc_IPInOutError_isLoaded;
  vector<float> *isotracks_miniIso_comb_nofsr_;
  TBranch *isotracks_miniIso_comb_nofsr_branch;
  bool isotracks_miniIso_comb_nofsr_isLoaded;
  vector<float> *muons_pfIso03_sum_charged_nofsr_;
  TBranch *muons_pfIso03_sum_charged_nofsr_branch;
  bool muons_pfIso03_sum_charged_nofsr_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghv4_0p25_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghv4_0p25_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghv4_0p25_MCFM_isLoaded;
  vector<unsigned int> *electrons_id_cutBased_Fall17V1_Veto_Bits_;
  TBranch *electrons_id_cutBased_Fall17V1_Veto_Bits_branch;
  bool electrons_id_cutBased_Fall17V1_Veto_Bits_isLoaded;
  vector<unsigned int> *photons_n_associated_pfcands_;
  TBranch *photons_n_associated_pfcands_branch;
  bool photons_n_associated_pfcands_isLoaded;
  float p_Gen_JJEW_SIG_ghv4_1_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv4_1_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv4_1_MCFM_isLoaded;
  vector<unsigned int> *electrons_id_MVA_HZZRun2Legacy_Iso_Cat_;
  TBranch *electrons_id_MVA_HZZRun2Legacy_Iso_Cat_branch;
  bool electrons_id_MVA_HZZRun2Legacy_Iso_Cat_isLoaded;
  float p_Gen_JJEW_SIG_ghv2_1_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv2_1_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv2_1_MCFM_isLoaded;
  vector<bool> *vtxs_is_good_;
  TBranch *vtxs_is_good_branch;
  bool vtxs_is_good_isLoaded;
  float puppimet_met_JERDn_;
  TBranch *puppimet_met_JERDn_branch;
  bool puppimet_met_JERDn_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_75E2_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_75E2_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_75E2_MCFM_isLoaded;
  vector<float> *electrons_scale_smear_corr_smear_totalDn_;
  TBranch *electrons_scale_smear_corr_smear_totalDn_branch;
  bool electrons_scale_smear_corr_smear_totalDn_isLoaded;
  vector<bool> *electrons_id_MVA_Fall17V2_Iso_pass_wp80_;
  TBranch *electrons_id_MVA_Fall17V2_Iso_pass_wp80_branch;
  bool electrons_id_MVA_Fall17V2_Iso_pass_wp80_isLoaded;
  float LHECandMass_;
  TBranch *LHECandMass_branch;
  bool LHECandMass_isLoaded;
  float pfmet_met_JERDn_;
  TBranch *pfmet_met_JERDn_branch;
  bool pfmet_met_JERDn_isLoaded;
  bool metfilter_goodVertices_;
  TBranch *metfilter_goodVertices_branch;
  bool metfilter_goodVertices_isLoaded;
  vector<float> *muons_pfIso04_sum_charged_nofsr_;
  TBranch *muons_pfIso04_sum_charged_nofsr_branch;
  bool muons_pfIso04_sum_charged_nofsr_isLoaded;
  float pfmet_met_JECUp_;
  TBranch *pfmet_met_JECUp_branch;
  bool pfmet_met_JECUp_isLoaded;
  vector<float> *ak4jets_JECDn_;
  TBranch *ak4jets_JECDn_branch;
  bool ak4jets_JECDn_isLoaded;
  vector<float> *electrons_pfIso03_comb_nofsr_;
  TBranch *electrons_pfIso03_comb_nofsr_branch;
  bool electrons_pfIso03_comb_nofsr_isLoaded;
  vector<float> *photons_pfIso_comb_;
  TBranch *photons_pfIso_comb_branch;
  bool photons_pfIso_comb_isLoaded;
  bool metfilter_trkPOG_toomanystripclus53X_;
  TBranch *metfilter_trkPOG_toomanystripclus53X_branch;
  bool metfilter_trkPOG_toomanystripclus53X_isLoaded;
  vector<float> *isotracks_pt_;
  TBranch *isotracks_pt_branch;
  bool isotracks_pt_isLoaded;
  vector<int> *lheparticles_mother1_index_;
  TBranch *lheparticles_mother1_index_branch;
  bool lheparticles_mother1_index_isLoaded;
  float pfmet_calo_met_;
  TBranch *pfmet_calo_met_branch;
  bool pfmet_calo_met_isLoaded;
  vector<float> *muons_pfIso03_comb_nofsr_;
  TBranch *muons_pfIso03_comb_nofsr_branch;
  bool muons_pfIso03_comb_nofsr_isLoaded;
  bool passCommonSkim_;
  TBranch *passCommonSkim_branch;
  bool passCommonSkim_isLoaded;
  vector<float> *muons_scale_smear_pt_corr_scale_totalUp_;
  TBranch *muons_scale_smear_pt_corr_scale_totalUp_branch;
  bool muons_scale_smear_pt_corr_scale_totalUp_isLoaded;
  vector<bool> *isotracks_is_tightTrack_;
  TBranch *isotracks_is_tightTrack_branch;
  bool isotracks_is_tightTrack_isLoaded;
  vector<unsigned int> *photons_id_cutBased_Fall17V2_Loose_Bits_;
  TBranch *photons_id_cutBased_Fall17V2_Loose_Bits_branch;
  bool photons_id_cutBased_Fall17V2_Loose_Bits_isLoaded;
  vector<unsigned long> *ak8jets_n_mucands_;
  TBranch *ak8jets_n_mucands_branch;
  bool ak8jets_n_mucands_isLoaded;
  bool metfilter_trkPOG_logErrorTooManyClusters_;
  TBranch *metfilter_trkPOG_logErrorTooManyClusters_branch;
  bool metfilter_trkPOG_logErrorTooManyClusters_isLoaded;
  vector<float> *ak8jets_axis2_;
  TBranch *ak8jets_axis2_branch;
  bool ak8jets_axis2_isLoaded;
  vector<bool> *isotracks_is_highPurityTrack_;
  TBranch *isotracks_is_highPurityTrack_branch;
  bool isotracks_is_highPurityTrack_isLoaded;
  float LHEweight_AsMZ_Up_NNPDF30_;
  TBranch *LHEweight_AsMZ_Up_NNPDF30_branch;
  bool LHEweight_AsMZ_Up_NNPDF30_isLoaded;
  vector<string> *triggers_name_;
  TBranch *triggers_name_branch;
  bool triggers_name_isLoaded;
  float puppimet_met_JECDn_;
  TBranch *puppimet_met_JECDn_branch;
  bool puppimet_met_JECDn_isLoaded;
  vector<float> *muons_miniIso_comb_nofsr_;
  TBranch *muons_miniIso_comb_nofsr_branch;
  bool muons_miniIso_comb_nofsr_isLoaded;
  vector<unsigned int> *electrons_id_cutBased_Fall17V2_Loose_Bits_;
  TBranch *electrons_id_cutBased_Fall17V2_Loose_Bits_branch;
  bool electrons_id_cutBased_Fall17V2_Loose_Bits_isLoaded;
  float p_Gen_JJEW_BSI_ghv1prime2_1E4_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv1prime2_1E4_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv1prime2_1E4_MCFM_isLoaded;
  vector<float> *electrons_id_MVA_HZZRun2Legacy_Iso_Val_;
  TBranch *electrons_id_MVA_HZZRun2Legacy_Iso_Val_branch;
  bool electrons_id_MVA_HZZRun2Legacy_Iso_Val_isLoaded;
  vector<float> *photons_pt_;
  TBranch *photons_pt_branch;
  bool photons_pt_isLoaded;
  bool metfilter_CSCTightHaloTrkMuUnvetoFilter_;
  TBranch *metfilter_CSCTightHaloTrkMuUnvetoFilter_branch;
  bool metfilter_CSCTightHaloTrkMuUnvetoFilter_isLoaded;
  vector<float> *electrons_miniIso_comb_nofsr_;
  TBranch *electrons_miniIso_comb_nofsr_branch;
  bool electrons_miniIso_comb_nofsr_isLoaded;
  vector<float> *muons_pull_dxdz_noArb_CSC_;
  TBranch *muons_pull_dxdz_noArb_CSC_branch;
  bool muons_pull_dxdz_noArb_CSC_isLoaded;
  bool metfilter_globalTightHalo2016Filter_;
  TBranch *metfilter_globalTightHalo2016Filter_branch;
  bool metfilter_globalTightHalo2016Filter_isLoaded;
  vector<int> *genparticles_status_;
  TBranch *genparticles_status_branch;
  bool genparticles_status_isLoaded;
  vector<bool> *genparticles_fromHardProcessDecayed_;
  TBranch *genparticles_fromHardProcessDecayed_branch;
  bool genparticles_fromHardProcessDecayed_isLoaded;
  float p_Gen_JJEW_BSI_ghv1_1_ghv4_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv1_1_ghv4_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv1_1_ghv4_1_MCFM_isLoaded;
  vector<bool> *genparticles_isPromptDecayed_;
  TBranch *genparticles_isPromptDecayed_branch;
  bool genparticles_isPromptDecayed_isLoaded;
  vector<bool> *ak4jets_pass_looseId_;
  TBranch *ak4jets_pass_looseId_branch;
  bool ak4jets_pass_looseId_isLoaded;
  bool metfilter_globalSuperTightHalo2016Filter_;
  TBranch *metfilter_globalSuperTightHalo2016Filter_branch;
  bool metfilter_globalSuperTightHalo2016Filter_isLoaded;
  vector<float> *muons_time_comb_IPInOut_;
  TBranch *muons_time_comb_IPInOut_branch;
  bool muons_time_comb_IPInOut_isLoaded;
  bool metfilter_ecalBadCalibFilterUpdated_;
  TBranch *metfilter_ecalBadCalibFilterUpdated_branch;
  bool metfilter_ecalBadCalibFilterUpdated_isLoaded;
  bool metfilter_HcalStripHaloFilter_;
  TBranch *metfilter_HcalStripHaloFilter_branch;
  bool metfilter_HcalStripHaloFilter_isLoaded;
  float genHEPMCweight_default_;
  TBranch *genHEPMCweight_default_branch;
  bool genHEPMCweight_default_isLoaded;
  vector<float> *photons_scale_smear_corr_scale_totalUp_;
  TBranch *photons_scale_smear_corr_scale_totalUp_branch;
  bool photons_scale_smear_corr_scale_totalUp_isLoaded;
  vector<float> *electrons_scale_smear_corr_scale_totalUp_;
  TBranch *electrons_scale_smear_corr_scale_totalUp_branch;
  bool electrons_scale_smear_corr_scale_totalUp_isLoaded;
  bool metfilter_trkPOG_manystripclus53X_;
  TBranch *metfilter_trkPOG_manystripclus53X_branch;
  bool metfilter_trkPOG_manystripclus53X_isLoaded;
  vector<int> *isotracks_id_;
  TBranch *isotracks_id_branch;
  bool isotracks_id_isLoaded;
  vector<float> *ak4jets_JECNominal_;
  TBranch *ak4jets_JECNominal_branch;
  bool ak4jets_JECNominal_isLoaded;
  float p_Gen_JJEW_BSI_gha4_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_gha4_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_gha4_1_MCFM_isLoaded;
  float LHEweight_PDFVariation_Dn_NNPDF30_;
  TBranch *LHEweight_PDFVariation_Dn_NNPDF30_branch;
  bool LHEweight_PDFVariation_Dn_NNPDF30_isLoaded;
  vector<float> *isotracks_dxy_;
  TBranch *isotracks_dxy_branch;
  bool isotracks_dxy_isLoaded;
  float pfmet_met_Raw_;
  TBranch *pfmet_met_Raw_branch;
  bool pfmet_met_Raw_isLoaded;
  vector<bool> *electrons_id_MVA_Fall17V2_Iso_pass_wp90_;
  TBranch *electrons_id_MVA_Fall17V2_Iso_pass_wp90_branch;
  bool electrons_id_MVA_Fall17V2_Iso_pass_wp90_isLoaded;
  vector<int> *genparticles_mom1_index_;
  TBranch *genparticles_mom1_index_branch;
  bool genparticles_mom1_index_isLoaded;
  vector<unsigned long> *ak8jets_n_pfcands_;
  TBranch *ak8jets_n_pfcands_branch;
  bool ak8jets_n_pfcands_isLoaded;
  float LHEweight_QCDscale_muR0p5_muF0p5_;
  TBranch *LHEweight_QCDscale_muR0p5_muF0p5_branch;
  bool LHEweight_QCDscale_muR0p5_muF0p5_isLoaded;
  float pfmet_met_JERUp_;
  TBranch *pfmet_met_JERUp_branch;
  bool pfmet_met_JERUp_isLoaded;
  bool metfilter_EcalDeadCellBoundaryEnergyFilter_;
  TBranch *metfilter_EcalDeadCellBoundaryEnergyFilter_branch;
  bool metfilter_EcalDeadCellBoundaryEnergyFilter_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghv2_0p25_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghv2_0p25_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghv2_0p25_MCFM_isLoaded;
  float pfmet_metPhi_JECUp_;
  TBranch *pfmet_metPhi_JECUp_branch;
  bool pfmet_metPhi_JECUp_isLoaded;
  float puppimet_metPhi_JERUp_;
  TBranch *puppimet_metPhi_JERUp_branch;
  bool puppimet_metPhi_JERUp_isLoaded;
  vector<float> *ak8jets_phi_;
  TBranch *ak8jets_phi_branch;
  bool ak8jets_phi_isLoaded;
  float pfmet_met_JECDn_;
  TBranch *pfmet_met_JECDn_branch;
  bool pfmet_met_JECDn_isLoaded;
  vector<bool> *photons_hasPixelSeed_;
  TBranch *photons_hasPixelSeed_branch;
  bool photons_hasPixelSeed_isLoaded;
  vector<float> *muons_time_rpc_IPOutInError_;
  TBranch *muons_time_rpc_IPOutInError_branch;
  bool muons_time_rpc_IPOutInError_isLoaded;
  float puppimet_metPhi_JECUp_;
  TBranch *puppimet_metPhi_JECUp_branch;
  bool puppimet_metPhi_JECUp_isLoaded;
  vector<unsigned int> *photons_id_MVA_Fall17V2_Cat_;
  TBranch *photons_id_MVA_Fall17V2_Cat_branch;
  bool photons_id_MVA_Fall17V2_Cat_isLoaded;
  vector<float> *ak8jets_JECDn_;
  TBranch *ak8jets_JECDn_branch;
  bool ak8jets_JECDn_isLoaded;
  vector<float> *fsrcands_eta_;
  TBranch *fsrcands_eta_branch;
  bool fsrcands_eta_isLoaded;
  vector<bool> *ak4jets_pass_puId_;
  TBranch *ak4jets_pass_puId_branch;
  bool ak4jets_pass_puId_isLoaded;
  float alphaS_;
  TBranch *alphaS_branch;
  bool alphaS_isLoaded;
  vector<unsigned long> *ak4jets_n_pfcands_;
  TBranch *ak4jets_n_pfcands_branch;
  bool ak4jets_n_pfcands_isLoaded;
  float p_Gen_JJEW_SIG_ghza2_1_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghza2_1_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghza2_1_MCFM_isLoaded;
  float puppimet_met_JERUp_;
  TBranch *puppimet_met_JERUp_branch;
  bool puppimet_met_JERUp_isLoaded;
  vector<float> *ak4jets_JECUp_;
  TBranch *ak4jets_JECUp_branch;
  bool ak4jets_JECUp_isLoaded;
  vector<vector<unsigned int> > *fsrcands_fsrMatch_muon_index_list_;
  TBranch *fsrcands_fsrMatch_muon_index_list_branch;
  bool fsrcands_fsrMatch_muon_index_list_isLoaded;
  vector<float> *muons_pfIso03_sum_neutral_nofsr_;
  TBranch *muons_pfIso03_sum_neutral_nofsr_branch;
  bool muons_pfIso03_sum_neutral_nofsr_isLoaded;
  vector<float> *muons_time_comb_IPOutIn_;
  TBranch *muons_time_comb_IPOutIn_branch;
  bool muons_time_comb_IPOutIn_isLoaded;
  vector<bool> *vtxs_is_fake_;
  TBranch *vtxs_is_fake_branch;
  bool vtxs_is_fake_isLoaded;
  float p_Gen_JJEW_SIG_gha2_1_MCFM_;
  TBranch *p_Gen_JJEW_SIG_gha2_1_MCFM_branch;
  bool p_Gen_JJEW_SIG_gha2_1_MCFM_isLoaded;
  float LHEweight_QCDscale_muR1_muF0p5_;
  TBranch *LHEweight_QCDscale_muR1_muF0p5_branch;
  bool LHEweight_QCDscale_muR1_muF0p5_isLoaded;
  vector<float> *genparticles_phi_;
  TBranch *genparticles_phi_branch;
  bool genparticles_phi_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghza4_0p5_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghza4_0p5_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghza4_0p5_MCFM_isLoaded;
  float pfmet_sumEt_Nominal_;
  TBranch *pfmet_sumEt_Nominal_branch;
  bool pfmet_sumEt_Nominal_isLoaded;
  bool metfilter_HBHENoiseFilter_;
  TBranch *metfilter_HBHENoiseFilter_branch;
  bool metfilter_HBHENoiseFilter_isLoaded;
  vector<float> *electrons_scale_smear_corr_;
  TBranch *electrons_scale_smear_corr_branch;
  bool electrons_scale_smear_corr_isLoaded;
  vector<bool> *genparticles_isLastCopy_;
  TBranch *genparticles_isLastCopy_branch;
  bool genparticles_isLastCopy_isLoaded;
  vector<int> *lheparticles_status_;
  TBranch *lheparticles_status_branch;
  bool lheparticles_status_isLoaded;
  vector<int> *isotracks_nearestPFcand_id_;
  TBranch *isotracks_nearestPFcand_id_branch;
  bool isotracks_nearestPFcand_id_isLoaded;
  float LHEweight_QCDscale_muR2_muF0p5_;
  TBranch *LHEweight_QCDscale_muR2_muF0p5_branch;
  bool LHEweight_QCDscale_muR2_muF0p5_isLoaded;
  vector<float> *isotracks_dzerr_;
  TBranch *isotracks_dzerr_branch;
  bool isotracks_dzerr_isLoaded;
  vector<float> *ak8jets_eta_;
  TBranch *ak8jets_eta_branch;
  bool ak8jets_eta_isLoaded;
  vector<bool> *genparticles_fromHardProcessBeforeFSR_;
  TBranch *genparticles_fromHardProcessBeforeFSR_branch;
  bool genparticles_fromHardProcessBeforeFSR_isLoaded;
  float pfmet_met_Nominal_;
  TBranch *pfmet_met_Nominal_branch;
  bool pfmet_met_Nominal_isLoaded;
  vector<float> *ak4jets_deepFlavourproblepb_;
  TBranch *ak4jets_deepFlavourproblepb_branch;
  bool ak4jets_deepFlavourproblepb_isLoaded;
  vector<float> *photons_pfNeutralHadronIso_EAcorr_;
  TBranch *photons_pfNeutralHadronIso_EAcorr_branch;
  bool photons_pfNeutralHadronIso_EAcorr_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_50E2_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_50E2_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_50E2_MCFM_isLoaded;
  vector<float> *vtxs_pos_y_;
  TBranch *vtxs_pos_y_branch;
  bool vtxs_pos_y_isLoaded;
  vector<float> *vtxs_pos_x_;
  TBranch *vtxs_pos_x_branch;
  bool vtxs_pos_x_isLoaded;
  vector<float> *vtxs_pos_z_;
  TBranch *vtxs_pos_z_branch;
  bool vtxs_pos_z_isLoaded;
  vector<float> *vtxs_pos_t_;
  TBranch *vtxs_pos_t_branch;
  bool vtxs_pos_t_isLoaded;
  vector<float> *ak8jets_area_;
  TBranch *ak8jets_area_branch;
  bool ak8jets_area_isLoaded;
  vector<bool> *genparticles_isDirectPromptTauDecayProductFinalState_;
  TBranch *genparticles_isDirectPromptTauDecayProductFinalState_branch;
  bool genparticles_isDirectPromptTauDecayProductFinalState_isLoaded;
  float xsecerr_;
  TBranch *xsecerr_branch;
  bool xsecerr_isLoaded;
  vector<bool> *photons_id_MVA_Fall17V2_pass_wp80_;
  TBranch *photons_id_MVA_Fall17V2_pass_wp80_branch;
  bool photons_id_MVA_Fall17V2_pass_wp80_isLoaded;
  vector<float> *muons_time_rpc_IPOutIn_;
  TBranch *muons_time_rpc_IPOutIn_branch;
  bool muons_time_rpc_IPOutIn_isLoaded;
  float LHEweight_QCDscale_muR2_muF2_;
  TBranch *LHEweight_QCDscale_muR2_muF2_branch;
  bool LHEweight_QCDscale_muR2_muF2_isLoaded;
  float LHEweight_QCDscale_muR2_muF1_;
  TBranch *LHEweight_QCDscale_muR2_muF1_branch;
  bool LHEweight_QCDscale_muR2_muF1_isLoaded;
  vector<float> *muons_mass_;
  TBranch *muons_mass_branch;
  bool muons_mass_isLoaded;
  vector<float> *muons_miniIso_sum_neutral_nofsr_;
  TBranch *muons_miniIso_sum_neutral_nofsr_branch;
  bool muons_miniIso_sum_neutral_nofsr_isLoaded;
  vector<float> *isotracks_phi_;
  TBranch *isotracks_phi_branch;
  bool isotracks_phi_isLoaded;
  vector<bool> *photons_passElectronVeto_;
  TBranch *photons_passElectronVeto_branch;
  bool photons_passElectronVeto_isLoaded;
  unsigned long long EventNumber_;
  TBranch *EventNumber_branch;
  bool EventNumber_isLoaded;
  vector<unsigned int> *electrons_id_cutBased_Fall17V1_Tight_Bits_;
  TBranch *electrons_id_cutBased_Fall17V1_Tight_Bits_branch;
  bool electrons_id_cutBased_Fall17V1_Tight_Bits_isLoaded;
  float p_Gen_JJEW_BSI_ghza2_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghza2_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghza2_1_MCFM_isLoaded;
  vector<float> *ak4jets_JERNominal_;
  TBranch *ak4jets_JERNominal_branch;
  bool ak4jets_JERNominal_isLoaded;
  vector<unsigned int> *electrons_n_associated_pfcands_;
  TBranch *electrons_n_associated_pfcands_branch;
  bool electrons_n_associated_pfcands_isLoaded;
  float pfmet_metSignificance_;
  TBranch *pfmet_metSignificance_branch;
  bool pfmet_metSignificance_isLoaded;
  vector<unsigned int> *electrons_type_mask_;
  TBranch *electrons_type_mask_branch;
  bool electrons_type_mask_isLoaded;
  vector<int> *ak8jets_hadronFlavour_;
  TBranch *ak8jets_hadronFlavour_branch;
  bool ak8jets_hadronFlavour_isLoaded;
  unsigned int vtxs_nvtxs_good_;
  TBranch *vtxs_nvtxs_good_branch;
  bool vtxs_nvtxs_good_isLoaded;
  vector<float> *photons_mass_;
  TBranch *photons_mass_branch;
  bool photons_mass_isLoaded;
  vector<float> *photons_scale_smear_corr_scale_totalDn_;
  TBranch *photons_scale_smear_corr_scale_totalDn_branch;
  bool photons_scale_smear_corr_scale_totalDn_isLoaded;
  float p_Gen_JJEW_BSI_ghv1_0p5_0p5i_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv1_0p5_0p5i_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv1_0p5_0p5i_MCFM_isLoaded;
  float puppimet_met_Nominal_;
  TBranch *puppimet_met_Nominal_branch;
  bool puppimet_met_Nominal_isLoaded;
  vector<float> *fsrcands_mass_;
  TBranch *fsrcands_mass_branch;
  bool fsrcands_mass_isLoaded;
  bool metfilter_BadPFMuonFilter_;
  TBranch *metfilter_BadPFMuonFilter_branch;
  bool metfilter_BadPFMuonFilter_isLoaded;
  vector<float> *electrons_pfIso03_sum_neutral_nofsr_;
  TBranch *electrons_pfIso03_sum_neutral_nofsr_branch;
  bool electrons_pfIso03_sum_neutral_nofsr_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_25E2_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_25E2_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_25E2_MCFM_isLoaded;
  vector<float> *ak8jets_mass_;
  TBranch *ak8jets_mass_branch;
  bool ak8jets_mass_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghza2_0p25_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghza2_0p25_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghza2_0p25_MCFM_isLoaded;
  float PythiaWeight_fsr_muRsqrt2_;
  TBranch *PythiaWeight_fsr_muRsqrt2_branch;
  bool PythiaWeight_fsr_muRsqrt2_isLoaded;
  float PythiaWeight_isr_muR0p5_;
  TBranch *PythiaWeight_isr_muR0p5_branch;
  bool PythiaWeight_isr_muR0p5_isLoaded;
  float genmet_metPhi_;
  TBranch *genmet_metPhi_branch;
  bool genmet_metPhi_isLoaded;
  int n_vtxs_PU_;
  TBranch *n_vtxs_PU_branch;
  bool n_vtxs_PU_isLoaded;
  float PythiaWeight_isr_muRoneoversqrt2_;
  TBranch *PythiaWeight_isr_muRoneoversqrt2_branch;
  bool PythiaWeight_isr_muRoneoversqrt2_isLoaded;
  vector<unsigned int> *electrons_id_MVA_Fall17V2_Iso_Cat_;
  TBranch *electrons_id_MVA_Fall17V2_Iso_Cat_branch;
  bool electrons_id_MVA_Fall17V2_Iso_Cat_isLoaded;
  vector<float> *isotracks_nearestPFcand_deltaR_;
  TBranch *isotracks_nearestPFcand_deltaR_branch;
  bool isotracks_nearestPFcand_deltaR_isLoaded;
  vector<float> *photons_eta_;
  TBranch *photons_eta_branch;
  bool photons_eta_isLoaded;
  vector<unsigned int> *photons_id_cutBased_Fall17V2_Tight_Bits_;
  TBranch *photons_id_cutBased_Fall17V2_Tight_Bits_branch;
  bool photons_id_cutBased_Fall17V2_Tight_Bits_isLoaded;
  vector<float> *ak8jets_axis1_;
  TBranch *ak8jets_axis1_branch;
  bool ak8jets_axis1_isLoaded;
  float pfmet_metPhi_JERUp_;
  TBranch *pfmet_metPhi_JERUp_branch;
  bool pfmet_metPhi_JERUp_isLoaded;
  float LHEweight_AsMZ_Dn_NNPDF30_;
  TBranch *LHEweight_AsMZ_Dn_NNPDF30_branch;
  bool LHEweight_AsMZ_Dn_NNPDF30_isLoaded;
  float pThat_;
  TBranch *pThat_branch;
  bool pThat_isLoaded;
  vector<float> *muons_scale_smear_pt_corr_;
  TBranch *muons_scale_smear_pt_corr_branch;
  bool muons_scale_smear_pt_corr_isLoaded;
  vector<int> *triggers_L1prescale_;
  TBranch *triggers_L1prescale_branch;
  bool triggers_L1prescale_isLoaded;
  vector<float> *isotracks_miniIso_ch_;
  TBranch *isotracks_miniIso_ch_branch;
  bool isotracks_miniIso_ch_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghv4_0p75_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghv4_0p75_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghv4_0p75_MCFM_isLoaded;
  vector<float> *electrons_scale_smear_corr_scale_totalDn_;
  TBranch *electrons_scale_smear_corr_scale_totalDn_branch;
  bool electrons_scale_smear_corr_scale_totalDn_isLoaded;
  vector<float> *electrons_pfIso03_sum_charged_nofsr_;
  TBranch *electrons_pfIso03_sum_charged_nofsr_branch;
  bool electrons_pfIso03_sum_charged_nofsr_isLoaded;
  bool metfilter_trackingFailureFilter_;
  TBranch *metfilter_trackingFailureFilter_branch;
  bool metfilter_trackingFailureFilter_isLoaded;
  vector<unsigned long> *ak8jets_n_softdrop_subjets_;
  TBranch *ak8jets_n_softdrop_subjets_branch;
  bool ak8jets_n_softdrop_subjets_isLoaded;
  vector<int> *muons_time_comb_ndof_;
  TBranch *muons_time_comb_ndof_branch;
  bool muons_time_comb_ndof_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_75E2_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_75E2_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_75E2_MCFM_isLoaded;
  float p_Gen_JJEW_BSI_ghza1prime2_1E4_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghza1prime2_1E4_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghza1prime2_1E4_MCFM_isLoaded;
  float puppimet_metPhi_JERDn_;
  TBranch *puppimet_metPhi_JERDn_branch;
  bool puppimet_metPhi_JERDn_isLoaded;
  float puppimet_sumEt_Raw_;
  TBranch *puppimet_sumEt_Raw_branch;
  bool puppimet_sumEt_Raw_isLoaded;
  vector<float> *photons_phi_;
  TBranch *photons_phi_branch;
  bool photons_phi_isLoaded;
  vector<int> *triggers_HLTprescale_;
  TBranch *triggers_HLTprescale_branch;
  bool triggers_HLTprescale_isLoaded;
  bool metfilter_trkPOGFilters_;
  TBranch *metfilter_trkPOGFilters_branch;
  bool metfilter_trkPOGFilters_isLoaded;
  vector<float> *ak8jets_pt_;
  TBranch *ak8jets_pt_branch;
  bool ak8jets_pt_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_50E2_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_50E2_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_50E2_MCFM_isLoaded;
  vector<float> *ak8jets_JECUp_;
  TBranch *ak8jets_JECUp_branch;
  bool ak8jets_JECUp_isLoaded;
  vector<float> *ak8jets_ptDistribution_;
  TBranch *ak8jets_ptDistribution_branch;
  bool ak8jets_ptDistribution_isLoaded;
  vector<int> *genparticles_id_;
  TBranch *genparticles_id_branch;
  bool genparticles_id_isLoaded;
  vector<float> *electrons_associated_pfcands_sum_sc_pt_;
  TBranch *electrons_associated_pfcands_sum_sc_pt_branch;
  bool electrons_associated_pfcands_sum_sc_pt_isLoaded;
  vector<float> *vtxs_pos_dt_;
  TBranch *vtxs_pos_dt_branch;
  bool vtxs_pos_dt_isLoaded;
  vector<float> *vtxs_pos_dz_;
  TBranch *vtxs_pos_dz_branch;
  bool vtxs_pos_dz_isLoaded;
  vector<float> *vtxs_pos_dx_;
  TBranch *vtxs_pos_dx_branch;
  bool vtxs_pos_dx_isLoaded;
  vector<float> *vtxs_pos_dy_;
  TBranch *vtxs_pos_dy_branch;
  bool vtxs_pos_dy_isLoaded;
  float puppimet_met_Raw_;
  TBranch *puppimet_met_Raw_branch;
  bool puppimet_met_Raw_isLoaded;
  vector<float> *ak4jets_mass_;
  TBranch *ak4jets_mass_branch;
  bool ak4jets_mass_isLoaded;
  vector<float> *vtxs_ndof_;
  TBranch *vtxs_ndof_branch;
  bool vtxs_ndof_isLoaded;
  vector<int> *muons_time_rpc_ndof_;
  TBranch *muons_time_rpc_ndof_branch;
  bool muons_time_rpc_ndof_isLoaded;
  vector<float> *ak8jets_JECNominal_;
  TBranch *ak8jets_JECNominal_branch;
  bool ak8jets_JECNominal_isLoaded;
  float puppimet_metSignificance_;
  TBranch *puppimet_metSignificance_branch;
  bool puppimet_metSignificance_isLoaded;
  vector<float> *isotracks_dz_;
  TBranch *isotracks_dz_branch;
  bool isotracks_dz_isLoaded;
  bool metfilter_chargedHadronTrackResolutionFilter_;
  TBranch *metfilter_chargedHadronTrackResolutionFilter_branch;
  bool metfilter_chargedHadronTrackResolutionFilter_isLoaded;
  bool metfilter_EcalDeadCellTriggerPrimitiveFilter_;
  TBranch *metfilter_EcalDeadCellTriggerPrimitiveFilter_branch;
  bool metfilter_EcalDeadCellTriggerPrimitiveFilter_isLoaded;
  vector<float> *fsrcands_phi_;
  TBranch *fsrcands_phi_branch;
  bool fsrcands_phi_isLoaded;
  float PythiaWeight_isr_muR2_;
  TBranch *PythiaWeight_isr_muR2_branch;
  bool PythiaWeight_isr_muR2_isLoaded;
  vector<float> *muons_scale_smear_pt_corr_smear_totalDn_;
  TBranch *muons_scale_smear_pt_corr_smear_totalDn_branch;
  bool muons_scale_smear_pt_corr_smear_totalDn_isLoaded;
  float PythiaWeight_isr_muR4_;
  TBranch *PythiaWeight_isr_muR4_branch;
  bool PythiaWeight_isr_muR4_isLoaded;
  vector<float> *ak8jets_pt_resolution_;
  TBranch *ak8jets_pt_resolution_branch;
  bool ak8jets_pt_resolution_isLoaded;
  vector<float> *electrons_id_MVA_Fall17V2_Iso_Val_;
  TBranch *electrons_id_MVA_Fall17V2_Iso_Val_branch;
  bool electrons_id_MVA_Fall17V2_Iso_Val_isLoaded;
  bool metfilter_hcalLaserEventFilter_;
  TBranch *metfilter_hcalLaserEventFilter_branch;
  bool metfilter_hcalLaserEventFilter_isLoaded;
  vector<bool> *isotracks_is_lostTrack_;
  TBranch *isotracks_is_lostTrack_branch;
  bool isotracks_is_lostTrack_isLoaded;
  vector<float> *electrons_pfIso04_comb_nofsr_;
  TBranch *electrons_pfIso04_comb_nofsr_branch;
  bool electrons_pfIso04_comb_nofsr_isLoaded;
  float p_Gen_JJEW_BSI_ghv1_1_gha2_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv1_1_gha2_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv1_1_gha2_1_MCFM_isLoaded;
  float p_Gen_JJEW_SIG_ghza1prime2_1E4_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghza1prime2_1E4_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghza1prime2_1E4_MCFM_isLoaded;
  float LHEweight_PDFVariation_Up_default_;
  TBranch *LHEweight_PDFVariation_Up_default_branch;
  bool LHEweight_PDFVariation_Up_default_isLoaded;
  vector<vector<unsigned int> > *fsrcands_fsrMatch_electron_index_list_;
  TBranch *fsrcands_fsrMatch_electron_index_list_branch;
  bool fsrcands_fsrMatch_electron_index_list_isLoaded;
  float n_true_int_;
  TBranch *n_true_int_branch;
  bool n_true_int_isLoaded;
  float p_Gen_JJEW_BSI_ghv2_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv2_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv2_1_MCFM_isLoaded;
  vector<float> *ak4jets_pt_;
  TBranch *ak4jets_pt_branch;
  bool ak4jets_pt_isLoaded;
  unsigned int RunNumber_;
  TBranch *RunNumber_branch;
  bool RunNumber_isLoaded;
  vector<unsigned int> *electrons_id_cutBased_Fall17V2_Tight_Bits_;
  TBranch *electrons_id_cutBased_Fall17V2_Tight_Bits_branch;
  bool electrons_id_cutBased_Fall17V2_Tight_Bits_isLoaded;
  vector<bool> *ak4jets_pass_leptonVetoId_;
  TBranch *ak4jets_pass_leptonVetoId_branch;
  bool ak4jets_pass_leptonVetoId_isLoaded;
  vector<float> *lheparticles_E_;
  TBranch *lheparticles_E_branch;
  bool lheparticles_E_isLoaded;
  vector<float> *isotracks_dxyerr_;
  TBranch *isotracks_dxyerr_branch;
  bool isotracks_dxyerr_isLoaded;
  float puppimet_metPhi_Raw_;
  TBranch *puppimet_metPhi_Raw_branch;
  bool puppimet_metPhi_Raw_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_gha2_0p75_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_gha2_0p75_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_gha2_0p75_MCFM_isLoaded;
  float PythiaWeight_fsr_muRoneoversqrt2_;
  TBranch *PythiaWeight_fsr_muRoneoversqrt2_branch;
  bool PythiaWeight_fsr_muRoneoversqrt2_isLoaded;
  vector<float> *ak4jets_ptDistribution_;
  TBranch *ak4jets_ptDistribution_branch;
  bool ak4jets_ptDistribution_isLoaded;
  vector<bool> *genparticles_isDirectHardProcessTauDecayProductFinalState_;
  TBranch *genparticles_isDirectHardProcessTauDecayProductFinalState_branch;
  bool genparticles_isDirectHardProcessTauDecayProductFinalState_isLoaded;
  vector<float> *isotracks_eta_;
  TBranch *isotracks_eta_branch;
  bool isotracks_eta_isLoaded;
  float p_Gen_JJEW_BSI_ghv1_1_ghza2_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv1_1_ghza2_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv1_1_ghza2_1_MCFM_isLoaded;
  vector<bool> *photons_id_MVA_Fall17V2_pass_wp90_;
  TBranch *photons_id_MVA_Fall17V2_pass_wp90_branch;
  bool photons_id_MVA_Fall17V2_pass_wp90_isLoaded;
  vector<vector<unsigned int> > *fsrcands_photonVeto_index_list_;
  TBranch *fsrcands_photonVeto_index_list_branch;
  bool fsrcands_photonVeto_index_list_isLoaded;
  bool metfilter_eeBadScFilter_;
  TBranch *metfilter_eeBadScFilter_branch;
  bool metfilter_eeBadScFilter_isLoaded;
  float puppimet_metPhi_Nominal_;
  TBranch *puppimet_metPhi_Nominal_branch;
  bool puppimet_metPhi_Nominal_isLoaded;
  vector<float> *photons_scale_smear_corr_smear_totalUp_;
  TBranch *photons_scale_smear_corr_smear_totalUp_branch;
  bool photons_scale_smear_corr_smear_totalUp_isLoaded;
  vector<unsigned long> *ak4jets_n_mucands_;
  TBranch *ak4jets_n_mucands_branch;
  bool ak4jets_n_mucands_isLoaded;
  bool metfilter_ecalBadCalibFilter_;
  TBranch *metfilter_ecalBadCalibFilter_branch;
  bool metfilter_ecalBadCalibFilter_isLoaded;
  vector<bool> *electrons_id_MVA_HZZRun2Legacy_Iso_pass_wpHZZ_;
  TBranch *electrons_id_MVA_HZZRun2Legacy_Iso_pass_wpHZZ_branch;
  bool electrons_id_MVA_HZZRun2Legacy_Iso_pass_wpHZZ_isLoaded;
  vector<float> *electrons_miniIso_sum_neutral_nofsr_;
  TBranch *electrons_miniIso_sum_neutral_nofsr_branch;
  bool electrons_miniIso_sum_neutral_nofsr_isLoaded;
  vector<int> *muons_charge_;
  TBranch *muons_charge_branch;
  bool muons_charge_isLoaded;
  vector<bool> *genparticles_is_packed_;
  TBranch *genparticles_is_packed_branch;
  bool genparticles_is_packed_isLoaded;
  vector<bool> *genparticles_isHardProcess_;
  TBranch *genparticles_isHardProcess_branch;
  bool genparticles_isHardProcess_isLoaded;
  vector<float> *muons_scale_smear_pt_corr_scale_totalDn_;
  TBranch *muons_scale_smear_pt_corr_scale_totalDn_branch;
  bool muons_scale_smear_pt_corr_scale_totalDn_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghza2_0p5_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghza2_0p5_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghza2_0p5_MCFM_isLoaded;
  float event_rho_;
  TBranch *event_rho_branch;
  bool event_rho_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghv2_0p75_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghv2_0p75_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghv2_0p75_MCFM_isLoaded;
  vector<int> *ak4jets_hadronFlavour_;
  TBranch *ak4jets_hadronFlavour_branch;
  bool ak4jets_hadronFlavour_isLoaded;
  vector<float> *ak4jets_pt_resolution_;
  TBranch *ak4jets_pt_resolution_branch;
  bool ak4jets_pt_resolution_isLoaded;
  float puppimet_sumEt_Nominal_;
  TBranch *puppimet_sumEt_Nominal_branch;
  bool puppimet_sumEt_Nominal_isLoaded;
  vector<bool> *electrons_id_MVA_Fall17V2_NoIso_pass_wp90_;
  TBranch *electrons_id_MVA_Fall17V2_NoIso_pass_wp90_branch;
  bool electrons_id_MVA_Fall17V2_NoIso_pass_wp90_isLoaded;
  vector<unsigned int> *electrons_id_MVA_Fall17V2_NoIso_Cat_;
  TBranch *electrons_id_MVA_Fall17V2_NoIso_Cat_branch;
  bool electrons_id_MVA_Fall17V2_NoIso_Cat_isLoaded;
  float pfmet_sumEt_Raw_;
  TBranch *pfmet_sumEt_Raw_branch;
  bool pfmet_sumEt_Raw_isLoaded;
  vector<float> *ak8jets_JERNominal_;
  TBranch *ak8jets_JERNominal_branch;
  bool ak8jets_JERNominal_isLoaded;
  vector<float> *genparticles_mass_;
  TBranch *genparticles_mass_branch;
  bool genparticles_mass_isLoaded;
  vector<unsigned int> *electrons_id_cutBased_Fall17V1_Loose_Bits_;
  TBranch *electrons_id_cutBased_Fall17V1_Loose_Bits_branch;
  bool electrons_id_cutBased_Fall17V1_Loose_Bits_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_MCFM_isLoaded;
  float LHEweight_QCDscale_muR0p5_muF1_;
  TBranch *LHEweight_QCDscale_muR0p5_muF1_branch;
  bool LHEweight_QCDscale_muR0p5_muF1_isLoaded;
  float LHEweight_QCDscale_muR0p5_muF2_;
  TBranch *LHEweight_QCDscale_muR0p5_muF2_branch;
  bool LHEweight_QCDscale_muR0p5_muF2_isLoaded;
  vector<float> *muons_pfIso04_sum_neutral_nofsr_;
  TBranch *muons_pfIso04_sum_neutral_nofsr_branch;
  bool muons_pfIso04_sum_neutral_nofsr_isLoaded;
  vector<int> *lheparticles_mother0_index_;
  TBranch *lheparticles_mother0_index_branch;
  bool lheparticles_mother0_index_isLoaded;
  bool metfilter_METFilters_;
  TBranch *metfilter_METFilters_branch;
  bool metfilter_METFilters_isLoaded;
  float pfmet_calo_metPhi_;
  TBranch *pfmet_calo_metPhi_branch;
  bool pfmet_calo_metPhi_isLoaded;
  float p_Gen_CPStoBWPropRewgt_;
  TBranch *p_Gen_CPStoBWPropRewgt_branch;
  bool p_Gen_CPStoBWPropRewgt_isLoaded;
  float puppimet_met_over_sqrtSumEt_;
  TBranch *puppimet_met_over_sqrtSumEt_branch;
  bool puppimet_met_over_sqrtSumEt_isLoaded;
  vector<float> *muons_phi_;
  TBranch *muons_phi_branch;
  bool muons_phi_isLoaded;
  vector<float> *muons_time_comb_IPInOutError_;
  TBranch *muons_time_comb_IPInOutError_branch;
  bool muons_time_comb_IPInOutError_isLoaded;
  float genHEPMCweight_NNPDF30_;
  TBranch *genHEPMCweight_NNPDF30_branch;
  bool genHEPMCweight_NNPDF30_isLoaded;
  vector<unsigned int> *electrons_id_cutBased_Fall17V2_Medium_Bits_;
  TBranch *electrons_id_cutBased_Fall17V2_Medium_Bits_branch;
  bool electrons_id_cutBased_Fall17V2_Medium_Bits_isLoaded;
  float pfmet_metPhi_JERDn_;
  TBranch *pfmet_metPhi_JERDn_branch;
  bool pfmet_metPhi_JERDn_isLoaded;
  vector<float> *ak4jets_deepFlavourprobc_;
  TBranch *ak4jets_deepFlavourprobc_branch;
  bool ak4jets_deepFlavourprobc_isLoaded;
  vector<float> *ak4jets_deepFlavourprobb_;
  TBranch *ak4jets_deepFlavourprobb_branch;
  bool ak4jets_deepFlavourprobb_isLoaded;
  vector<float> *ak4jets_deepFlavourprobg_;
  TBranch *ak4jets_deepFlavourprobg_branch;
  bool ak4jets_deepFlavourprobg_isLoaded;
  float LHEweight_QCDscale_muR1_muF2_;
  TBranch *LHEweight_QCDscale_muR1_muF2_branch;
  bool LHEweight_QCDscale_muR1_muF2_isLoaded;
  float LHEweight_QCDscale_muR1_muF1_;
  TBranch *LHEweight_QCDscale_muR1_muF1_branch;
  bool LHEweight_QCDscale_muR1_muF1_isLoaded;
  bool metfilter_BadChargedCandidateFilter_;
  TBranch *metfilter_BadChargedCandidateFilter_branch;
  bool metfilter_BadChargedCandidateFilter_isLoaded;
  float sumEt_;
  TBranch *sumEt_branch;
  bool sumEt_isLoaded;
  vector<float> *ak8jets_JERDn_;
  TBranch *ak8jets_JERDn_branch;
  bool ak8jets_JERDn_isLoaded;
  float p_Gen_JJEW_BSI_ghv1_1_gha4_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv1_1_gha4_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv1_1_gha4_1_MCFM_isLoaded;
  vector<float> *muons_miniIso_sum_charged_nofsr_;
  TBranch *muons_miniIso_sum_charged_nofsr_branch;
  bool muons_miniIso_sum_charged_nofsr_isLoaded;
  vector<unsigned int> *muons_POG_selector_bits_;
  TBranch *muons_POG_selector_bits_branch;
  bool muons_POG_selector_bits_isLoaded;
  vector<float> *photons_pfChargedHadronIso_EAcorr_;
  TBranch *photons_pfChargedHadronIso_EAcorr_branch;
  bool photons_pfChargedHadronIso_EAcorr_isLoaded;
  float p_Gen_JJEW_BSI_ghv4_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv4_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv4_1_MCFM_isLoaded;
  vector<float> *isotracks_pfIso03_ch_;
  TBranch *isotracks_pfIso03_ch_branch;
  bool isotracks_pfIso03_ch_isLoaded;
  vector<float> *electrons_phi_;
  TBranch *electrons_phi_branch;
  bool electrons_phi_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_gha2_0p25_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_gha2_0p25_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_gha2_0p25_MCFM_isLoaded;
  float LHEweight_PDFVariation_Dn_default_;
  TBranch *LHEweight_PDFVariation_Dn_default_branch;
  bool LHEweight_PDFVariation_Dn_default_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_25E2_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_25E2_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_25E2_MCFM_isLoaded;
  vector<float> *ak4jets_phi_;
  TBranch *ak4jets_phi_branch;
  bool ak4jets_phi_isLoaded;
  vector<unsigned int> *photons_id_cutBased_Fall17V2_Medium_Bits_;
  TBranch *photons_id_cutBased_Fall17V2_Medium_Bits_branch;
  bool photons_id_cutBased_Fall17V2_Medium_Bits_isLoaded;
  vector<float> *ak4jets_area_;
  TBranch *ak4jets_area_branch;
  bool ak4jets_area_isLoaded;
  vector<int> *electrons_charge_;
  TBranch *electrons_charge_branch;
  bool electrons_charge_isLoaded;
  vector<float> *muons_eta_;
  TBranch *muons_eta_branch;
  bool muons_eta_isLoaded;
  vector<bool> *vtxs_is_valid_;
  TBranch *vtxs_is_valid_branch;
  bool vtxs_is_valid_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghza2_0p75_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghza2_0p75_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghza2_0p75_MCFM_isLoaded;
  vector<float> *electrons_miniIso_sum_charged_nofsr_;
  TBranch *electrons_miniIso_sum_charged_nofsr_branch;
  bool electrons_miniIso_sum_charged_nofsr_isLoaded;
  vector<float> *ak4jets_deepFlavourprobbb_;
  TBranch *ak4jets_deepFlavourprobbb_branch;
  bool ak4jets_deepFlavourprobbb_isLoaded;
  float LHEweight_AsMZ_Up_default_;
  TBranch *LHEweight_AsMZ_Up_default_branch;
  bool LHEweight_AsMZ_Up_default_isLoaded;
  vector<float> *muons_miniIso_comb_nofsr_uncorrected_;
  TBranch *muons_miniIso_comb_nofsr_uncorrected_branch;
  bool muons_miniIso_comb_nofsr_uncorrected_isLoaded;
  bool metfilter_CSCTightHalo2015Filter_;
  TBranch *metfilter_CSCTightHalo2015Filter_branch;
  bool metfilter_CSCTightHalo2015Filter_isLoaded;
  vector<bool> *genparticles_isPromptFinalState_;
  TBranch *genparticles_isPromptFinalState_branch;
  bool genparticles_isPromptFinalState_isLoaded;
  vector<float> *muons_time_comb_IPOutInError_;
  TBranch *muons_time_comb_IPOutInError_branch;
  bool muons_time_comb_IPOutInError_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_gha2_0p5_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_gha2_0p5_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_gha2_0p5_MCFM_isLoaded;
  vector<float> *electrons_etaSC_;
  TBranch *electrons_etaSC_branch;
  bool electrons_etaSC_isLoaded;
  float p_Gen_JJEW_BSI_ghv1_1_ghv1prime2_1E4_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv1_1_ghv1prime2_1E4_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv1_1_ghv1prime2_1E4_MCFM_isLoaded;
  vector<float> *photons_associated_pfcands_sum_sc_pt_;
  TBranch *photons_associated_pfcands_sum_sc_pt_branch;
  bool photons_associated_pfcands_sum_sc_pt_isLoaded;
  float PythiaWeight_fsr_muR0p25_;
  TBranch *PythiaWeight_fsr_muR0p25_branch;
  bool PythiaWeight_fsr_muR0p25_isLoaded;
  float PythiaWeight_isr_muRsqrt2_;
  TBranch *PythiaWeight_isr_muRsqrt2_branch;
  bool PythiaWeight_isr_muRsqrt2_isLoaded;
  vector<float> *ak4jets_deepFlavourprobuds_;
  TBranch *ak4jets_deepFlavourprobuds_branch;
  bool ak4jets_deepFlavourprobuds_isLoaded;
  float p_Gen_JJEW_BSI_ghv1_1_ghza1prime2_1E4_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghv1_1_ghza1prime2_1E4_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghv1_1_ghza1prime2_1E4_MCFM_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_gha4_0p25_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_gha4_0p25_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_gha4_0p25_MCFM_isLoaded;
  vector<float> *electrons_pfIso04_sum_neutral_nofsr_;
  TBranch *electrons_pfIso04_sum_neutral_nofsr_branch;
  bool electrons_pfIso04_sum_neutral_nofsr_isLoaded;
  bool metfilter_ecalLaserCorrFilter_;
  TBranch *metfilter_ecalLaserCorrFilter_branch;
  bool metfilter_ecalLaserCorrFilter_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghza4_0p25_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghza4_0p25_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghza4_0p25_MCFM_isLoaded;
  bool metfilter_HBHENoiseIsoFilter_;
  TBranch *metfilter_HBHENoiseIsoFilter_branch;
  bool metfilter_HBHENoiseIsoFilter_isLoaded;
  float p_Gen_JJEW_SIG_ghv1_1_ghza4_0p75_MCFM_;
  TBranch *p_Gen_JJEW_SIG_ghv1_1_ghza4_0p75_MCFM_branch;
  bool p_Gen_JJEW_SIG_ghv1_1_ghza4_0p75_MCFM_isLoaded;
  float p_Gen_JJEW_BSI_ghza4_1_MCFM_;
  TBranch *p_Gen_JJEW_BSI_ghza4_1_MCFM_branch;
  bool p_Gen_JJEW_BSI_ghza4_1_MCFM_isLoaded;
  float PythiaWeight_isr_muR0p25_;
  TBranch *PythiaWeight_isr_muR0p25_branch;
  bool PythiaWeight_isr_muR0p25_isLoaded;
  float genmet_met_;
  TBranch *genmet_met_branch;
  bool genmet_met_isLoaded;
  vector<float> *fsrcands_pt_;
  TBranch *fsrcands_pt_branch;
  bool fsrcands_pt_isLoaded;
  vector<bool> *genparticles_fromHardProcessFinalState_;
  TBranch *genparticles_fromHardProcessFinalState_branch;
  bool genparticles_fromHardProcessFinalState_isLoaded;
  vector<float> *ak4jets_JERUp_;
  TBranch *ak4jets_JERUp_branch;
  bool ak4jets_JERUp_isLoaded;
  vector<float> *photons_id_MVA_Fall17V2_Val_;
  TBranch *photons_id_MVA_Fall17V2_Val_branch;
  bool photons_id_MVA_Fall17V2_Val_isLoaded;
  vector<float> *genparticles_eta_;
  TBranch *genparticles_eta_branch;
  bool genparticles_eta_isLoaded;
  vector<float> *ak4jets_axis1_;
  TBranch *ak4jets_axis1_branch;
  bool ak4jets_axis1_isLoaded;
  vector<float> *ak4jets_axis2_;
  TBranch *ak4jets_axis2_branch;
  bool ak4jets_axis2_isLoaded;
  float puppimet_met_JECUp_;
  TBranch *puppimet_met_JECUp_branch;
  bool puppimet_met_JECUp_isLoaded;
  vector<bool> *electrons_id_MVA_Fall17V2_Iso_pass_wpLoose_;
  TBranch *electrons_id_MVA_Fall17V2_Iso_pass_wpLoose_branch;
  bool electrons_id_MVA_Fall17V2_Iso_pass_wpLoose_isLoaded;
  vector<float> *electrons_id_MVA_Fall17V2_NoIso_Val_;
  TBranch *electrons_id_MVA_Fall17V2_NoIso_Val_branch;
  bool electrons_id_MVA_Fall17V2_NoIso_Val_isLoaded;
  float PythiaWeight_fsr_muR2_;
  TBranch *PythiaWeight_fsr_muR2_branch;
  bool PythiaWeight_fsr_muR2_isLoaded;
  float pfmet_met_over_sqrtSumEt_;
  TBranch *pfmet_met_over_sqrtSumEt_branch;
  bool pfmet_met_over_sqrtSumEt_isLoaded;
  float PythiaWeight_fsr_muR4_;
  TBranch *PythiaWeight_fsr_muR4_branch;
  bool PythiaWeight_fsr_muR4_isLoaded;
  vector<int> *lheparticles_id_;
  TBranch *lheparticles_id_branch;
  bool lheparticles_id_isLoaded;
  vector<bool> *electrons_id_MVA_Fall17V2_Iso_pass_wpHZZ_;
  TBranch *electrons_id_MVA_Fall17V2_Iso_pass_wpHZZ_branch;
  bool electrons_id_MVA_Fall17V2_Iso_pass_wpHZZ_isLoaded;
  vector<float> *electrons_scale_smear_corr_smear_totalUp_;
  TBranch *electrons_scale_smear_corr_smear_totalUp_branch;
  bool electrons_scale_smear_corr_smear_totalUp_isLoaded;
  vector<float> *isotracks_mass_;
  TBranch *isotracks_mass_branch;
  bool isotracks_mass_isLoaded;
  vector<bool> *triggers_passTrigger_;
  TBranch *triggers_passTrigger_branch;
  bool triggers_passTrigger_isLoaded;
  float pfmet_metPhi_Raw_;
  TBranch *pfmet_metPhi_Raw_branch;
  bool pfmet_metPhi_Raw_isLoaded;
  float LHEweight_PDFVariation_Up_NNPDF30_;
  TBranch *LHEweight_PDFVariation_Up_NNPDF30_branch;
  bool LHEweight_PDFVariation_Up_NNPDF30_isLoaded;
  vector<float> *photons_pfEMIso_EAcorr_;
  TBranch *photons_pfEMIso_EAcorr_branch;
  bool photons_pfEMIso_EAcorr_isLoaded;
  vector<float> *ak8jets_JERUp_;
  TBranch *ak8jets_JERUp_branch;
  bool ak8jets_JERUp_isLoaded;
  vector<unsigned int> *electrons_id_cutBased_Fall17V1_Medium_Bits_;
  TBranch *electrons_id_cutBased_Fall17V1_Medium_Bits_branch;
  bool electrons_id_cutBased_Fall17V1_Medium_Bits_isLoaded;
  vector<float> *lheparticles_px_;
  TBranch *lheparticles_px_branch;
  bool lheparticles_px_isLoaded;
  bool metfilter_muonBadTrackFilter_;
  TBranch *metfilter_muonBadTrackFilter_branch;
  bool metfilter_muonBadTrackFilter_isLoaded;
  vector<float> *photons_scale_smear_corr_smear_totalDn_;
  TBranch *photons_scale_smear_corr_smear_totalDn_branch;
  bool photons_scale_smear_corr_smear_totalDn_isLoaded;
public:
  void Init(TTree *tree);
  void GetEntry(unsigned int idx);
  void LoadAllBranches();
  const float &p_Gen_GG_SIG_kappaTopBot_1_ghz1_1_MCFM();
  const float &p_Gen_GG_BSI_kappaTopBot_1_ghz1_1_MCFM();
  const float &p_Gen_JJEW_SIG_ghza4_1_MCFM();
  const vector<int> &ak8jets_partonFlavour();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghv2_1_MCFM();
  const vector<float> &electrons_eta();
  const vector<float> &electrons_pfIso04_sum_charged_nofsr();
  const vector<float> &lheparticles_pz();
  const vector<bool> &ak4jets_pass_tightId();
  const vector<float> &lheparticles_py();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V2_Veto_Bits();
  const float &pfmet_metPhi_Nominal();
  const float &xsec();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha4_0p75_MCFM();
  const vector<float> &electrons_miniIso_comb_nofsr_uncorrected();
  const vector<bool> &genparticles_isLastCopyBeforeFSR();
  const vector<float> &muons_pfIso04_comb_nofsr();
  const vector<bool> &isotracks_is_pfCand();
  const bool &metfilter_CSCTightHaloFilter();
  const vector<float> &muons_time_rpc_IPInOut();
  const vector<float> &muons_pt();
  const float &p_Gen_JJEW_SIG_gha4_1_MCFM();
  const vector<bool> &electrons_id_MVA_Fall17V2_NoIso_pass_wpLoose();
  const vector<float> &photons_scale_smear_corr();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv2_0p5_MCFM();
  const vector<unsigned int> &electrons_fid_mask();
  const float &LHEweight_AsMZ_Dn_default();
  const vector<float> &electrons_mass();
  const float &pfmet_metPhi_JECDn();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv4_0p5_MCFM();
  const vector<float> &ak4jets_JERDn();
  const float &xsec_lhe();
  const vector<int> &ak4jets_partonFlavour();
  const vector<float> &ak4jets_eta();
  const vector<float> &ak4jets_totalMultiplicity();
  const float &puppimet_metPhi_JECDn();
  const vector<float> &electrons_pt();
  const vector<float> &genparticles_pt();
  const float &PythiaWeight_fsr_muR0p5();
  const vector<int> &genparticles_mom0_index();
  const float &p_Gen_JJEW_SIG_ghv1prime2_1E4_MCFM();
  const vector<float> &muons_pull_dxdz_noArb_DT();
  const vector<float> &ak8jets_totalMultiplicity();
  const float &p_Gen_JJEW_BKG_MCFM();
  const float &p_Gen_JJEW_BSI_gha2_1_MCFM();
  const vector<bool> &isotracks_fromPV();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha4_0p5_MCFM();
  const float &p_Gen_JJEW_BSI_ghv1_1_MCFM();
  const vector<float> &muons_scale_smear_pt_corr_smear_totalUp();
  const vector<bool> &electrons_id_MVA_Fall17V2_NoIso_pass_wp80();
  const vector<float> &isotracks_pfIso03_comb_nofsr();
  const unsigned int &LuminosityBlock();
  const unsigned int &vtxs_nvtxs();
  const float &qscale();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghza4_1_MCFM();
  const vector<float> &muons_time_rpc_IPInOutError();
  const vector<float> &isotracks_miniIso_comb_nofsr();
  const vector<float> &muons_pfIso03_sum_charged_nofsr();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv4_0p25_MCFM();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V1_Veto_Bits();
  const vector<unsigned int> &photons_n_associated_pfcands();
  const float &p_Gen_JJEW_SIG_ghv4_1_MCFM();
  const vector<unsigned int> &electrons_id_MVA_HZZRun2Legacy_Iso_Cat();
  const float &p_Gen_JJEW_SIG_ghv2_1_MCFM();
  const vector<bool> &vtxs_is_good();
  const float &puppimet_met_JERDn();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_75E2_MCFM();
  const vector<float> &electrons_scale_smear_corr_smear_totalDn();
  const vector<bool> &electrons_id_MVA_Fall17V2_Iso_pass_wp80();
  const float &LHECandMass();
  const float &pfmet_met_JERDn();
  const bool &metfilter_goodVertices();
  const vector<float> &muons_pfIso04_sum_charged_nofsr();
  const float &pfmet_met_JECUp();
  const vector<float> &ak4jets_JECDn();
  const vector<float> &electrons_pfIso03_comb_nofsr();
  const vector<float> &photons_pfIso_comb();
  const bool &metfilter_trkPOG_toomanystripclus53X();
  const vector<float> &isotracks_pt();
  const vector<int> &lheparticles_mother1_index();
  const float &pfmet_calo_met();
  const vector<float> &muons_pfIso03_comb_nofsr();
  const bool &passCommonSkim();
  const vector<float> &muons_scale_smear_pt_corr_scale_totalUp();
  const vector<bool> &isotracks_is_tightTrack();
  const vector<unsigned int> &photons_id_cutBased_Fall17V2_Loose_Bits();
  const vector<unsigned long> &ak8jets_n_mucands();
  const bool &metfilter_trkPOG_logErrorTooManyClusters();
  const vector<float> &ak8jets_axis2();
  const vector<bool> &isotracks_is_highPurityTrack();
  const float &LHEweight_AsMZ_Up_NNPDF30();
  const vector<string> &triggers_name();
  const float &puppimet_met_JECDn();
  const vector<float> &muons_miniIso_comb_nofsr();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V2_Loose_Bits();
  const float &p_Gen_JJEW_BSI_ghv1prime2_1E4_MCFM();
  const vector<float> &electrons_id_MVA_HZZRun2Legacy_Iso_Val();
  const vector<float> &photons_pt();
  const bool &metfilter_CSCTightHaloTrkMuUnvetoFilter();
  const vector<float> &electrons_miniIso_comb_nofsr();
  const vector<float> &muons_pull_dxdz_noArb_CSC();
  const bool &metfilter_globalTightHalo2016Filter();
  const vector<int> &genparticles_status();
  const vector<bool> &genparticles_fromHardProcessDecayed();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghv4_1_MCFM();
  const vector<bool> &genparticles_isPromptDecayed();
  const vector<bool> &ak4jets_pass_looseId();
  const bool &metfilter_globalSuperTightHalo2016Filter();
  const vector<float> &muons_time_comb_IPInOut();
  const bool &metfilter_ecalBadCalibFilterUpdated();
  const bool &metfilter_HcalStripHaloFilter();
  const float &genHEPMCweight_default();
  const vector<float> &photons_scale_smear_corr_scale_totalUp();
  const vector<float> &electrons_scale_smear_corr_scale_totalUp();
  const bool &metfilter_trkPOG_manystripclus53X();
  const vector<int> &isotracks_id();
  const vector<float> &ak4jets_JECNominal();
  const float &p_Gen_JJEW_BSI_gha4_1_MCFM();
  const float &LHEweight_PDFVariation_Dn_NNPDF30();
  const vector<float> &isotracks_dxy();
  const float &pfmet_met_Raw();
  const vector<bool> &electrons_id_MVA_Fall17V2_Iso_pass_wp90();
  const vector<int> &genparticles_mom1_index();
  const vector<unsigned long> &ak8jets_n_pfcands();
  const float &LHEweight_QCDscale_muR0p5_muF0p5();
  const float &pfmet_met_JERUp();
  const bool &metfilter_EcalDeadCellBoundaryEnergyFilter();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv2_0p25_MCFM();
  const float &pfmet_metPhi_JECUp();
  const float &puppimet_metPhi_JERUp();
  const vector<float> &ak8jets_phi();
  const float &pfmet_met_JECDn();
  const vector<bool> &photons_hasPixelSeed();
  const vector<float> &muons_time_rpc_IPOutInError();
  const float &puppimet_metPhi_JECUp();
  const vector<unsigned int> &photons_id_MVA_Fall17V2_Cat();
  const vector<float> &ak8jets_JECDn();
  const vector<float> &fsrcands_eta();
  const vector<bool> &ak4jets_pass_puId();
  const float &alphaS();
  const vector<unsigned long> &ak4jets_n_pfcands();
  const float &p_Gen_JJEW_SIG_ghza2_1_MCFM();
  const float &puppimet_met_JERUp();
  const vector<float> &ak4jets_JECUp();
  const vector<vector<unsigned int> > &fsrcands_fsrMatch_muon_index_list();
  const vector<float> &muons_pfIso03_sum_neutral_nofsr();
  const vector<float> &muons_time_comb_IPOutIn();
  const vector<bool> &vtxs_is_fake();
  const float &p_Gen_JJEW_SIG_gha2_1_MCFM();
  const float &LHEweight_QCDscale_muR1_muF0p5();
  const vector<float> &genparticles_phi();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza4_0p5_MCFM();
  const float &pfmet_sumEt_Nominal();
  const bool &metfilter_HBHENoiseFilter();
  const vector<float> &electrons_scale_smear_corr();
  const vector<bool> &genparticles_isLastCopy();
  const vector<int> &lheparticles_status();
  const vector<int> &isotracks_nearestPFcand_id();
  const float &LHEweight_QCDscale_muR2_muF0p5();
  const vector<float> &isotracks_dzerr();
  const vector<float> &ak8jets_eta();
  const vector<bool> &genparticles_fromHardProcessBeforeFSR();
  const float &pfmet_met_Nominal();
  const vector<float> &ak4jets_deepFlavourproblepb();
  const vector<float> &photons_pfNeutralHadronIso_EAcorr();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_50E2_MCFM();
  const vector<float> &vtxs_pos_y();
  const vector<float> &vtxs_pos_x();
  const vector<float> &vtxs_pos_z();
  const vector<float> &vtxs_pos_t();
  const vector<float> &ak8jets_area();
  const vector<bool> &genparticles_isDirectPromptTauDecayProductFinalState();
  const float &xsecerr();
  const vector<bool> &photons_id_MVA_Fall17V2_pass_wp80();
  const vector<float> &muons_time_rpc_IPOutIn();
  const float &LHEweight_QCDscale_muR2_muF2();
  const float &LHEweight_QCDscale_muR2_muF1();
  const vector<float> &muons_mass();
  const vector<float> &muons_miniIso_sum_neutral_nofsr();
  const vector<float> &isotracks_phi();
  const vector<bool> &photons_passElectronVeto();
  const unsigned long long &EventNumber();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V1_Tight_Bits();
  const float &p_Gen_JJEW_BSI_ghza2_1_MCFM();
  const vector<float> &ak4jets_JERNominal();
  const vector<unsigned int> &electrons_n_associated_pfcands();
  const float &pfmet_metSignificance();
  const vector<unsigned int> &electrons_type_mask();
  const vector<int> &ak8jets_hadronFlavour();
  const unsigned int &vtxs_nvtxs_good();
  const vector<float> &photons_mass();
  const vector<float> &photons_scale_smear_corr_scale_totalDn();
  const float &p_Gen_JJEW_BSI_ghv1_0p5_0p5i_MCFM();
  const float &puppimet_met_Nominal();
  const vector<float> &fsrcands_mass();
  const bool &metfilter_BadPFMuonFilter();
  const vector<float> &electrons_pfIso03_sum_neutral_nofsr();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_25E2_MCFM();
  const vector<float> &ak8jets_mass();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza2_0p25_MCFM();
  const float &PythiaWeight_fsr_muRsqrt2();
  const float &PythiaWeight_isr_muR0p5();
  const float &genmet_metPhi();
  const int &n_vtxs_PU();
  const float &PythiaWeight_isr_muRoneoversqrt2();
  const vector<unsigned int> &electrons_id_MVA_Fall17V2_Iso_Cat();
  const vector<float> &isotracks_nearestPFcand_deltaR();
  const vector<float> &photons_eta();
  const vector<unsigned int> &photons_id_cutBased_Fall17V2_Tight_Bits();
  const vector<float> &ak8jets_axis1();
  const float &pfmet_metPhi_JERUp();
  const float &LHEweight_AsMZ_Dn_NNPDF30();
  const float &pThat();
  const vector<float> &muons_scale_smear_pt_corr();
  const vector<int> &triggers_L1prescale();
  const vector<float> &isotracks_miniIso_ch();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv4_0p75_MCFM();
  const vector<float> &electrons_scale_smear_corr_scale_totalDn();
  const vector<float> &electrons_pfIso03_sum_charged_nofsr();
  const bool &metfilter_trackingFailureFilter();
  const vector<unsigned long> &ak8jets_n_softdrop_subjets();
  const vector<int> &muons_time_comb_ndof();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_75E2_MCFM();
  const float &p_Gen_JJEW_BSI_ghza1prime2_1E4_MCFM();
  const float &puppimet_metPhi_JERDn();
  const float &puppimet_sumEt_Raw();
  const vector<float> &photons_phi();
  const vector<int> &triggers_HLTprescale();
  const bool &metfilter_trkPOGFilters();
  const vector<float> &ak8jets_pt();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_50E2_MCFM();
  const vector<float> &ak8jets_JECUp();
  const vector<float> &ak8jets_ptDistribution();
  const vector<int> &genparticles_id();
  const vector<float> &electrons_associated_pfcands_sum_sc_pt();
  const vector<float> &vtxs_pos_dt();
  const vector<float> &vtxs_pos_dz();
  const vector<float> &vtxs_pos_dx();
  const vector<float> &vtxs_pos_dy();
  const float &puppimet_met_Raw();
  const vector<float> &ak4jets_mass();
  const vector<float> &vtxs_ndof();
  const vector<int> &muons_time_rpc_ndof();
  const vector<float> &ak8jets_JECNominal();
  const float &puppimet_metSignificance();
  const vector<float> &isotracks_dz();
  const bool &metfilter_chargedHadronTrackResolutionFilter();
  const bool &metfilter_EcalDeadCellTriggerPrimitiveFilter();
  const vector<float> &fsrcands_phi();
  const float &PythiaWeight_isr_muR2();
  const vector<float> &muons_scale_smear_pt_corr_smear_totalDn();
  const float &PythiaWeight_isr_muR4();
  const vector<float> &ak8jets_pt_resolution();
  const vector<float> &electrons_id_MVA_Fall17V2_Iso_Val();
  const bool &metfilter_hcalLaserEventFilter();
  const vector<bool> &isotracks_is_lostTrack();
  const vector<float> &electrons_pfIso04_comb_nofsr();
  const float &p_Gen_JJEW_BSI_ghv1_1_gha2_1_MCFM();
  const float &p_Gen_JJEW_SIG_ghza1prime2_1E4_MCFM();
  const float &LHEweight_PDFVariation_Up_default();
  const vector<vector<unsigned int> > &fsrcands_fsrMatch_electron_index_list();
  const float &n_true_int();
  const float &p_Gen_JJEW_BSI_ghv2_1_MCFM();
  const vector<float> &ak4jets_pt();
  const unsigned int &RunNumber();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V2_Tight_Bits();
  const vector<bool> &ak4jets_pass_leptonVetoId();
  const vector<float> &lheparticles_E();
  const vector<float> &isotracks_dxyerr();
  const float &puppimet_metPhi_Raw();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha2_0p75_MCFM();
  const float &PythiaWeight_fsr_muRoneoversqrt2();
  const vector<float> &ak4jets_ptDistribution();
  const vector<bool> &genparticles_isDirectHardProcessTauDecayProductFinalState();
  const vector<float> &isotracks_eta();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghza2_1_MCFM();
  const vector<bool> &photons_id_MVA_Fall17V2_pass_wp90();
  const vector<vector<unsigned int> > &fsrcands_photonVeto_index_list();
  const bool &metfilter_eeBadScFilter();
  const float &puppimet_metPhi_Nominal();
  const vector<float> &photons_scale_smear_corr_smear_totalUp();
  const vector<unsigned long> &ak4jets_n_mucands();
  const bool &metfilter_ecalBadCalibFilter();
  const vector<bool> &electrons_id_MVA_HZZRun2Legacy_Iso_pass_wpHZZ();
  const vector<float> &electrons_miniIso_sum_neutral_nofsr();
  const vector<int> &muons_charge();
  const vector<bool> &genparticles_is_packed();
  const vector<bool> &genparticles_isHardProcess();
  const vector<float> &muons_scale_smear_pt_corr_scale_totalDn();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza2_0p5_MCFM();
  const float &event_rho();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv2_0p75_MCFM();
  const vector<int> &ak4jets_hadronFlavour();
  const vector<float> &ak4jets_pt_resolution();
  const float &puppimet_sumEt_Nominal();
  const vector<bool> &electrons_id_MVA_Fall17V2_NoIso_pass_wp90();
  const vector<unsigned int> &electrons_id_MVA_Fall17V2_NoIso_Cat();
  const float &pfmet_sumEt_Raw();
  const vector<float> &ak8jets_JERNominal();
  const vector<float> &genparticles_mass();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V1_Loose_Bits();
  const float &p_Gen_JJEW_SIG_ghv1_1_MCFM();
  const float &LHEweight_QCDscale_muR0p5_muF1();
  const float &LHEweight_QCDscale_muR0p5_muF2();
  const vector<float> &muons_pfIso04_sum_neutral_nofsr();
  const vector<int> &lheparticles_mother0_index();
  const bool &metfilter_METFilters();
  const float &pfmet_calo_metPhi();
  const float &p_Gen_CPStoBWPropRewgt();
  const float &puppimet_met_over_sqrtSumEt();
  const vector<float> &muons_phi();
  const vector<float> &muons_time_comb_IPInOutError();
  const float &genHEPMCweight_NNPDF30();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V2_Medium_Bits();
  const float &pfmet_metPhi_JERDn();
  const vector<float> &ak4jets_deepFlavourprobc();
  const vector<float> &ak4jets_deepFlavourprobb();
  const vector<float> &ak4jets_deepFlavourprobg();
  const float &LHEweight_QCDscale_muR1_muF2();
  const float &LHEweight_QCDscale_muR1_muF1();
  const bool &metfilter_BadChargedCandidateFilter();
  const float &sumEt();
  const vector<float> &ak8jets_JERDn();
  const float &p_Gen_JJEW_BSI_ghv1_1_gha4_1_MCFM();
  const vector<float> &muons_miniIso_sum_charged_nofsr();
  const vector<unsigned int> &muons_POG_selector_bits();
  const vector<float> &photons_pfChargedHadronIso_EAcorr();
  const float &p_Gen_JJEW_BSI_ghv4_1_MCFM();
  const vector<float> &isotracks_pfIso03_ch();
  const vector<float> &electrons_phi();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha2_0p25_MCFM();
  const float &LHEweight_PDFVariation_Dn_default();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_25E2_MCFM();
  const vector<float> &ak4jets_phi();
  const vector<unsigned int> &photons_id_cutBased_Fall17V2_Medium_Bits();
  const vector<float> &ak4jets_area();
  const vector<int> &electrons_charge();
  const vector<float> &muons_eta();
  const vector<bool> &vtxs_is_valid();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza2_0p75_MCFM();
  const vector<float> &electrons_miniIso_sum_charged_nofsr();
  const vector<float> &ak4jets_deepFlavourprobbb();
  const float &LHEweight_AsMZ_Up_default();
  const vector<float> &muons_miniIso_comb_nofsr_uncorrected();
  const bool &metfilter_CSCTightHalo2015Filter();
  const vector<bool> &genparticles_isPromptFinalState();
  const vector<float> &muons_time_comb_IPOutInError();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha2_0p5_MCFM();
  const vector<float> &electrons_etaSC();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghv1prime2_1E4_MCFM();
  const vector<float> &photons_associated_pfcands_sum_sc_pt();
  const float &PythiaWeight_fsr_muR0p25();
  const float &PythiaWeight_isr_muRsqrt2();
  const vector<float> &ak4jets_deepFlavourprobuds();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghza1prime2_1E4_MCFM();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha4_0p25_MCFM();
  const vector<float> &electrons_pfIso04_sum_neutral_nofsr();
  const bool &metfilter_ecalLaserCorrFilter();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza4_0p25_MCFM();
  const bool &metfilter_HBHENoiseIsoFilter();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza4_0p75_MCFM();
  const float &p_Gen_JJEW_BSI_ghza4_1_MCFM();
  const float &PythiaWeight_isr_muR0p25();
  const float &genmet_met();
  const vector<float> &fsrcands_pt();
  const vector<bool> &genparticles_fromHardProcessFinalState();
  const vector<float> &ak4jets_JERUp();
  const vector<float> &photons_id_MVA_Fall17V2_Val();
  const vector<float> &genparticles_eta();
  const vector<float> &ak4jets_axis1();
  const vector<float> &ak4jets_axis2();
  const float &puppimet_met_JECUp();
  const vector<bool> &electrons_id_MVA_Fall17V2_Iso_pass_wpLoose();
  const vector<float> &electrons_id_MVA_Fall17V2_NoIso_Val();
  const float &PythiaWeight_fsr_muR2();
  const float &pfmet_met_over_sqrtSumEt();
  const float &PythiaWeight_fsr_muR4();
  const vector<int> &lheparticles_id();
  const vector<bool> &electrons_id_MVA_Fall17V2_Iso_pass_wpHZZ();
  const vector<float> &electrons_scale_smear_corr_smear_totalUp();
  const vector<float> &isotracks_mass();
  const vector<bool> &triggers_passTrigger();
  const float &pfmet_metPhi_Raw();
  const float &LHEweight_PDFVariation_Up_NNPDF30();
  const vector<float> &photons_pfEMIso_EAcorr();
  const vector<float> &ak8jets_JERUp();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V1_Medium_Bits();
  const vector<float> &lheparticles_px();
  const bool &metfilter_muonBadTrackFilter();
  const vector<float> &photons_scale_smear_corr_smear_totalDn();
  static void progress( int nEventsTotal, int nEventsChain );
};

#ifndef __CINT__
extern CMS5 cms5;
#endif

namespace tas {

  const float &p_Gen_JJEW_SIG_ghza4_1_MCFM();
  const vector<int> &ak8jets_partonFlavour();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghv2_1_MCFM();
  const vector<float> &electrons_eta();
  const vector<float> &electrons_pfIso04_sum_charged_nofsr();
  const vector<float> &lheparticles_pz();
  const vector<bool> &ak4jets_pass_tightId();
  const vector<float> &lheparticles_py();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V2_Veto_Bits();
  const float &pfmet_metPhi_Nominal();
  const float &xsec();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha4_0p75_MCFM();
  const vector<float> &electrons_miniIso_comb_nofsr_uncorrected();
  const vector<bool> &genparticles_isLastCopyBeforeFSR();
  const vector<float> &muons_pfIso04_comb_nofsr();
  const vector<bool> &isotracks_is_pfCand();
  const bool &metfilter_CSCTightHaloFilter();
  const vector<float> &muons_time_rpc_IPInOut();
  const vector<float> &muons_pt();
  const float &p_Gen_JJEW_SIG_gha4_1_MCFM();
  const vector<bool> &electrons_id_MVA_Fall17V2_NoIso_pass_wpLoose();
  const vector<float> &photons_scale_smear_corr();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv2_0p5_MCFM();
  const vector<unsigned int> &electrons_fid_mask();
  const float &LHEweight_AsMZ_Dn_default();
  const vector<float> &electrons_mass();
  const float &pfmet_metPhi_JECDn();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv4_0p5_MCFM();
  const vector<float> &ak4jets_JERDn();
  const float &xsec_lhe();
  const vector<int> &ak4jets_partonFlavour();
  const vector<float> &ak4jets_eta();
  const vector<float> &ak4jets_totalMultiplicity();
  const float &puppimet_metPhi_JECDn();
  const vector<float> &electrons_pt();
  const vector<float> &genparticles_pt();
  const float &PythiaWeight_fsr_muR0p5();
  const vector<int> &genparticles_mom0_index();
  const float &p_Gen_JJEW_SIG_ghv1prime2_1E4_MCFM();
  const vector<float> &muons_pull_dxdz_noArb_DT();
  const vector<float> &ak8jets_totalMultiplicity();
  const float &p_Gen_JJEW_BKG_MCFM();
  const float &p_Gen_JJEW_BSI_gha2_1_MCFM();
  const vector<bool> &isotracks_fromPV();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha4_0p5_MCFM();
  const float &p_Gen_JJEW_BSI_ghv1_1_MCFM();
  const vector<float> &muons_scale_smear_pt_corr_smear_totalUp();
  const vector<bool> &electrons_id_MVA_Fall17V2_NoIso_pass_wp80();
  const vector<float> &isotracks_pfIso03_comb_nofsr();
  const unsigned int &LuminosityBlock();
  const unsigned int &vtxs_nvtxs();
  const float &qscale();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghza4_1_MCFM();
  const vector<float> &muons_time_rpc_IPInOutError();
  const vector<float> &isotracks_miniIso_comb_nofsr();
  const vector<float> &muons_pfIso03_sum_charged_nofsr();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv4_0p25_MCFM();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V1_Veto_Bits();
  const vector<unsigned int> &photons_n_associated_pfcands();
  const float &p_Gen_JJEW_SIG_ghv4_1_MCFM();
  const vector<unsigned int> &electrons_id_MVA_HZZRun2Legacy_Iso_Cat();
  const float &p_Gen_JJEW_SIG_ghv2_1_MCFM();
  const vector<bool> &vtxs_is_good();
  const float &puppimet_met_JERDn();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_75E2_MCFM();
  const vector<float> &electrons_scale_smear_corr_smear_totalDn();
  const vector<bool> &electrons_id_MVA_Fall17V2_Iso_pass_wp80();
  const float &LHECandMass();
  const float &pfmet_met_JERDn();
  const bool &metfilter_goodVertices();
  const vector<float> &muons_pfIso04_sum_charged_nofsr();
  const float &pfmet_met_JECUp();
  const vector<float> &ak4jets_JECDn();
  const vector<float> &electrons_pfIso03_comb_nofsr();
  const vector<float> &photons_pfIso_comb();
  const bool &metfilter_trkPOG_toomanystripclus53X();
  const vector<float> &isotracks_pt();
  const vector<int> &lheparticles_mother1_index();
  const float &pfmet_calo_met();
  const vector<float> &muons_pfIso03_comb_nofsr();
  const bool &passCommonSkim();
  const vector<float> &muons_scale_smear_pt_corr_scale_totalUp();
  const vector<bool> &isotracks_is_tightTrack();
  const vector<unsigned int> &photons_id_cutBased_Fall17V2_Loose_Bits();
  const vector<unsigned long> &ak8jets_n_mucands();
  const bool &metfilter_trkPOG_logErrorTooManyClusters();
  const vector<float> &ak8jets_axis2();
  const vector<bool> &isotracks_is_highPurityTrack();
  const float &LHEweight_AsMZ_Up_NNPDF30();
  const vector<string> &triggers_name();
  const float &puppimet_met_JECDn();
  const vector<float> &muons_miniIso_comb_nofsr();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V2_Loose_Bits();
  const float &p_Gen_JJEW_BSI_ghv1prime2_1E4_MCFM();
  const vector<float> &electrons_id_MVA_HZZRun2Legacy_Iso_Val();
  const vector<float> &photons_pt();
  const bool &metfilter_CSCTightHaloTrkMuUnvetoFilter();
  const vector<float> &electrons_miniIso_comb_nofsr();
  const vector<float> &muons_pull_dxdz_noArb_CSC();
  const bool &metfilter_globalTightHalo2016Filter();
  const vector<int> &genparticles_status();
  const vector<bool> &genparticles_fromHardProcessDecayed();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghv4_1_MCFM();
  const vector<bool> &genparticles_isPromptDecayed();
  const vector<bool> &ak4jets_pass_looseId();
  const bool &metfilter_globalSuperTightHalo2016Filter();
  const vector<float> &muons_time_comb_IPInOut();
  const bool &metfilter_ecalBadCalibFilterUpdated();
  const bool &metfilter_HcalStripHaloFilter();
  const float &genHEPMCweight_default();
  const vector<float> &photons_scale_smear_corr_scale_totalUp();
  const vector<float> &electrons_scale_smear_corr_scale_totalUp();
  const bool &metfilter_trkPOG_manystripclus53X();
  const vector<int> &isotracks_id();
  const vector<float> &ak4jets_JECNominal();
  const float &p_Gen_JJEW_BSI_gha4_1_MCFM();
  const float &LHEweight_PDFVariation_Dn_NNPDF30();
  const vector<float> &isotracks_dxy();
  const float &pfmet_met_Raw();
  const vector<bool> &electrons_id_MVA_Fall17V2_Iso_pass_wp90();
  const vector<int> &genparticles_mom1_index();
  const vector<unsigned long> &ak8jets_n_pfcands();
  const float &LHEweight_QCDscale_muR0p5_muF0p5();
  const float &pfmet_met_JERUp();
  const bool &metfilter_EcalDeadCellBoundaryEnergyFilter();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv2_0p25_MCFM();
  const float &pfmet_metPhi_JECUp();
  const float &puppimet_metPhi_JERUp();
  const vector<float> &ak8jets_phi();
  const float &pfmet_met_JECDn();
  const vector<bool> &photons_hasPixelSeed();
  const vector<float> &muons_time_rpc_IPOutInError();
  const float &puppimet_metPhi_JECUp();
  const vector<unsigned int> &photons_id_MVA_Fall17V2_Cat();
  const vector<float> &ak8jets_JECDn();
  const vector<float> &fsrcands_eta();
  const vector<bool> &ak4jets_pass_puId();
  const float &alphaS();
  const vector<unsigned long> &ak4jets_n_pfcands();
  const float &p_Gen_JJEW_SIG_ghza2_1_MCFM();
  const float &puppimet_met_JERUp();
  const vector<float> &ak4jets_JECUp();
  const vector<vector<unsigned int> > &fsrcands_fsrMatch_muon_index_list();
  const vector<float> &muons_pfIso03_sum_neutral_nofsr();
  const vector<float> &muons_time_comb_IPOutIn();
  const vector<bool> &vtxs_is_fake();
  const float &p_Gen_JJEW_SIG_gha2_1_MCFM();
  const float &LHEweight_QCDscale_muR1_muF0p5();
  const vector<float> &genparticles_phi();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza4_0p5_MCFM();
  const float &pfmet_sumEt_Nominal();
  const bool &metfilter_HBHENoiseFilter();
  const vector<float> &electrons_scale_smear_corr();
  const vector<bool> &genparticles_isLastCopy();
  const vector<int> &lheparticles_status();
  const vector<int> &isotracks_nearestPFcand_id();
  const float &LHEweight_QCDscale_muR2_muF0p5();
  const vector<float> &isotracks_dzerr();
  const vector<float> &ak8jets_eta();
  const vector<bool> &genparticles_fromHardProcessBeforeFSR();
  const float &pfmet_met_Nominal();
  const vector<float> &ak4jets_deepFlavourproblepb();
  const vector<float> &photons_pfNeutralHadronIso_EAcorr();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_50E2_MCFM();
  const vector<float> &vtxs_pos_y();
  const vector<float> &vtxs_pos_x();
  const vector<float> &vtxs_pos_z();
  const vector<float> &vtxs_pos_t();
  const vector<float> &ak8jets_area();
  const vector<bool> &genparticles_isDirectPromptTauDecayProductFinalState();
  const float &xsecerr();
  const vector<bool> &photons_id_MVA_Fall17V2_pass_wp80();
  const vector<float> &muons_time_rpc_IPOutIn();
  const float &LHEweight_QCDscale_muR2_muF2();
  const float &LHEweight_QCDscale_muR2_muF1();
  const vector<float> &muons_mass();
  const vector<float> &muons_miniIso_sum_neutral_nofsr();
  const vector<float> &isotracks_phi();
  const vector<bool> &photons_passElectronVeto();
  const unsigned long long &EventNumber();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V1_Tight_Bits();
  const float &p_Gen_JJEW_BSI_ghza2_1_MCFM();
  const vector<float> &ak4jets_JERNominal();
  const vector<unsigned int> &electrons_n_associated_pfcands();
  const float &pfmet_metSignificance();
  const vector<unsigned int> &electrons_type_mask();
  const vector<int> &ak8jets_hadronFlavour();
  const unsigned int &vtxs_nvtxs_good();
  const vector<float> &photons_mass();
  const vector<float> &photons_scale_smear_corr_scale_totalDn();
  const float &p_Gen_JJEW_BSI_ghv1_0p5_0p5i_MCFM();
  const float &puppimet_met_Nominal();
  const vector<float> &fsrcands_mass();
  const bool &metfilter_BadPFMuonFilter();
  const vector<float> &electrons_pfIso03_sum_neutral_nofsr();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv1prime2_25E2_MCFM();
  const vector<float> &ak8jets_mass();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza2_0p25_MCFM();
  const float &PythiaWeight_fsr_muRsqrt2();
  const float &PythiaWeight_isr_muR0p5();
  const float &genmet_metPhi();
  const int &n_vtxs_PU();
  const float &PythiaWeight_isr_muRoneoversqrt2();
  const vector<unsigned int> &electrons_id_MVA_Fall17V2_Iso_Cat();
  const vector<float> &isotracks_nearestPFcand_deltaR();
  const vector<float> &photons_eta();
  const vector<unsigned int> &photons_id_cutBased_Fall17V2_Tight_Bits();
  const vector<float> &ak8jets_axis1();
  const float &pfmet_metPhi_JERUp();
  const float &LHEweight_AsMZ_Dn_NNPDF30();
  const float &pThat();
  const vector<float> &muons_scale_smear_pt_corr();
  const vector<int> &triggers_L1prescale();
  const vector<float> &isotracks_miniIso_ch();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv4_0p75_MCFM();
  const vector<float> &electrons_scale_smear_corr_scale_totalDn();
  const vector<float> &electrons_pfIso03_sum_charged_nofsr();
  const bool &metfilter_trackingFailureFilter();
  const vector<unsigned long> &ak8jets_n_softdrop_subjets();
  const vector<int> &muons_time_comb_ndof();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_75E2_MCFM();
  const float &p_Gen_JJEW_BSI_ghza1prime2_1E4_MCFM();
  const float &puppimet_metPhi_JERDn();
  const float &puppimet_sumEt_Raw();
  const vector<float> &photons_phi();
  const vector<int> &triggers_HLTprescale();
  const bool &metfilter_trkPOGFilters();
  const vector<float> &ak8jets_pt();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_50E2_MCFM();
  const vector<float> &ak8jets_JECUp();
  const vector<float> &ak8jets_ptDistribution();
  const vector<int> &genparticles_id();
  const vector<float> &electrons_associated_pfcands_sum_sc_pt();
  const vector<float> &vtxs_pos_dt();
  const vector<float> &vtxs_pos_dz();
  const vector<float> &vtxs_pos_dx();
  const vector<float> &vtxs_pos_dy();
  const float &puppimet_met_Raw();
  const vector<float> &ak4jets_mass();
  const vector<float> &vtxs_ndof();
  const vector<int> &muons_time_rpc_ndof();
  const vector<float> &ak8jets_JECNominal();
  const float &puppimet_metSignificance();
  const vector<float> &isotracks_dz();
  const bool &metfilter_chargedHadronTrackResolutionFilter();
  const bool &metfilter_EcalDeadCellTriggerPrimitiveFilter();
  const vector<float> &fsrcands_phi();
  const float &PythiaWeight_isr_muR2();
  const vector<float> &muons_scale_smear_pt_corr_smear_totalDn();
  const float &PythiaWeight_isr_muR4();
  const vector<float> &ak8jets_pt_resolution();
  const vector<float> &electrons_id_MVA_Fall17V2_Iso_Val();
  const bool &metfilter_hcalLaserEventFilter();
  const vector<bool> &isotracks_is_lostTrack();
  const vector<float> &electrons_pfIso04_comb_nofsr();
  const float &p_Gen_JJEW_BSI_ghv1_1_gha2_1_MCFM();
  const float &p_Gen_JJEW_SIG_ghza1prime2_1E4_MCFM();
  const float &LHEweight_PDFVariation_Up_default();
  const vector<vector<unsigned int> > &fsrcands_fsrMatch_electron_index_list();
  const float &n_true_int();
  const float &p_Gen_JJEW_BSI_ghv2_1_MCFM();
  const vector<float> &ak4jets_pt();
  const unsigned int &RunNumber();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V2_Tight_Bits();
  const vector<bool> &ak4jets_pass_leptonVetoId();
  const vector<float> &lheparticles_E();
  const vector<float> &isotracks_dxyerr();
  const float &puppimet_metPhi_Raw();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha2_0p75_MCFM();
  const float &PythiaWeight_fsr_muRoneoversqrt2();
  const vector<float> &ak4jets_ptDistribution();
  const vector<bool> &genparticles_isDirectHardProcessTauDecayProductFinalState();
  const vector<float> &isotracks_eta();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghza2_1_MCFM();
  const vector<bool> &photons_id_MVA_Fall17V2_pass_wp90();
  const vector<vector<unsigned int> > &fsrcands_photonVeto_index_list();
  const bool &metfilter_eeBadScFilter();
  const float &puppimet_metPhi_Nominal();
  const vector<float> &photons_scale_smear_corr_smear_totalUp();
  const vector<unsigned long> &ak4jets_n_mucands();
  const bool &metfilter_ecalBadCalibFilter();
  const vector<bool> &electrons_id_MVA_HZZRun2Legacy_Iso_pass_wpHZZ();
  const vector<float> &electrons_miniIso_sum_neutral_nofsr();
  const vector<int> &muons_charge();
  const vector<bool> &genparticles_is_packed();
  const vector<bool> &genparticles_isHardProcess();
  const vector<float> &muons_scale_smear_pt_corr_scale_totalDn();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza2_0p5_MCFM();
  const float &event_rho();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghv2_0p75_MCFM();
  const vector<int> &ak4jets_hadronFlavour();
  const vector<float> &ak4jets_pt_resolution();
  const float &puppimet_sumEt_Nominal();
  const vector<bool> &electrons_id_MVA_Fall17V2_NoIso_pass_wp90();
  const vector<unsigned int> &electrons_id_MVA_Fall17V2_NoIso_Cat();
  const float &pfmet_sumEt_Raw();
  const vector<float> &ak8jets_JERNominal();
  const vector<float> &genparticles_mass();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V1_Loose_Bits();
  const float &p_Gen_JJEW_SIG_ghv1_1_MCFM();
  const float &LHEweight_QCDscale_muR0p5_muF1();
  const float &LHEweight_QCDscale_muR0p5_muF2();
  const vector<float> &muons_pfIso04_sum_neutral_nofsr();
  const vector<int> &lheparticles_mother0_index();
  const bool &metfilter_METFilters();
  const float &pfmet_calo_metPhi();
  const float &p_Gen_CPStoBWPropRewgt();
  const float &puppimet_met_over_sqrtSumEt();
  const vector<float> &muons_phi();
  const vector<float> &muons_time_comb_IPInOutError();
  const float &genHEPMCweight_NNPDF30();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V2_Medium_Bits();
  const float &pfmet_metPhi_JERDn();
  const vector<float> &ak4jets_deepFlavourprobc();
  const vector<float> &ak4jets_deepFlavourprobb();
  const vector<float> &ak4jets_deepFlavourprobg();
  const float &LHEweight_QCDscale_muR1_muF2();
  const float &LHEweight_QCDscale_muR1_muF1();
  const bool &metfilter_BadChargedCandidateFilter();
  const float &sumEt();
  const vector<float> &ak8jets_JERDn();
  const float &p_Gen_JJEW_BSI_ghv1_1_gha4_1_MCFM();
  const vector<float> &muons_miniIso_sum_charged_nofsr();
  const vector<unsigned int> &muons_POG_selector_bits();
  const vector<float> &photons_pfChargedHadronIso_EAcorr();
  const float &p_Gen_JJEW_BSI_ghv4_1_MCFM();
  const vector<float> &isotracks_pfIso03_ch();
  const vector<float> &electrons_phi();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha2_0p25_MCFM();
  const float &LHEweight_PDFVariation_Dn_default();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza1prime2_25E2_MCFM();
  const vector<float> &ak4jets_phi();
  const vector<unsigned int> &photons_id_cutBased_Fall17V2_Medium_Bits();
  const vector<float> &ak4jets_area();
  const vector<int> &electrons_charge();
  const vector<float> &muons_eta();
  const vector<bool> &vtxs_is_valid();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza2_0p75_MCFM();
  const vector<float> &electrons_miniIso_sum_charged_nofsr();
  const vector<float> &ak4jets_deepFlavourprobbb();
  const float &LHEweight_AsMZ_Up_default();
  const vector<float> &muons_miniIso_comb_nofsr_uncorrected();
  const bool &metfilter_CSCTightHalo2015Filter();
  const vector<bool> &genparticles_isPromptFinalState();
  const vector<float> &muons_time_comb_IPOutInError();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha2_0p5_MCFM();
  const vector<float> &electrons_etaSC();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghv1prime2_1E4_MCFM();
  const vector<float> &photons_associated_pfcands_sum_sc_pt();
  const float &PythiaWeight_fsr_muR0p25();
  const float &PythiaWeight_isr_muRsqrt2();
  const vector<float> &ak4jets_deepFlavourprobuds();
  const float &p_Gen_JJEW_BSI_ghv1_1_ghza1prime2_1E4_MCFM();
  const float &p_Gen_JJEW_SIG_ghv1_1_gha4_0p25_MCFM();
  const vector<float> &electrons_pfIso04_sum_neutral_nofsr();
  const bool &metfilter_ecalLaserCorrFilter();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza4_0p25_MCFM();
  const bool &metfilter_HBHENoiseIsoFilter();
  const float &p_Gen_JJEW_SIG_ghv1_1_ghza4_0p75_MCFM();
  const float &p_Gen_JJEW_BSI_ghza4_1_MCFM();
  const float &PythiaWeight_isr_muR0p25();
  const float &genmet_met();
  const vector<float> &fsrcands_pt();
  const vector<bool> &genparticles_fromHardProcessFinalState();
  const vector<float> &ak4jets_JERUp();
  const vector<float> &photons_id_MVA_Fall17V2_Val();
  const vector<float> &genparticles_eta();
  const vector<float> &ak4jets_axis1();
  const vector<float> &ak4jets_axis2();
  const float &puppimet_met_JECUp();
  const vector<bool> &electrons_id_MVA_Fall17V2_Iso_pass_wpLoose();
  const vector<float> &electrons_id_MVA_Fall17V2_NoIso_Val();
  const float &PythiaWeight_fsr_muR2();
  const float &pfmet_met_over_sqrtSumEt();
  const float &PythiaWeight_fsr_muR4();
  const vector<int> &lheparticles_id();
  const vector<bool> &electrons_id_MVA_Fall17V2_Iso_pass_wpHZZ();
  const vector<float> &electrons_scale_smear_corr_smear_totalUp();
  const vector<float> &isotracks_mass();
  const vector<bool> &triggers_passTrigger();
  const float &pfmet_metPhi_Raw();
  const float &LHEweight_PDFVariation_Up_NNPDF30();
  const vector<float> &photons_pfEMIso_EAcorr();
  const vector<float> &ak8jets_JERUp();
  const vector<unsigned int> &electrons_id_cutBased_Fall17V1_Medium_Bits();
  const vector<float> &lheparticles_px();
  const bool &metfilter_muonBadTrackFilter();
  const vector<float> &photons_scale_smear_corr_smear_totalDn();
  const float &p_Gen_GG_SIG_kappaTopBot_1_ghz1_1_MCFM();
  const float &p_Gen_GG_BSI_kappaTopBot_1_ghz1_1_MCFM();
}
#endif
